# Exploratory Data Analysis (EDA)

We want to explore the raw data that we claimed from `EngSaf` to answer these questions:
1. It is clean enough to be used in our model training and evaluation?
2. How many missing values there?
3. How many duplications?
4. What is the semantic similarity between the train, validation and unseen data?
5. Is there data leakages between train, validation and test data?
6. What actions should be taken according to the missing, duplicated and leakage values?
7. What is the final (clean) training size will be?
8. How should we split the validation and test sets (size for each)?
9. What is the maximum length (word-based) in both train and unseen sets?
10. Is the static prompt length + maximum length is larger than the maximum model length?

In [2]:
import os
import json
import pandas as pd
import faiss
from sentence_transformers import SentenceTransformer

#### The raw data that we claimed from `EngSaf` are downloaded and saved in `raw` dir

In [3]:
raw_datasets  = "raw"

dataset_files = [file for file in os.listdir(raw_datasets) if file.endswith(".csv")]

dataset_files

['val.csv', 'unseen_answers.csv', 'unseen_question.csv', 'train.csv']

## Train Dataset
Here is a summary of the insights and finds of the raw train set:
1. the data contains missing values in both `Question_id` and `Student Answer`.
2. we will drop the `Question_id` there is no need for it.
3. we will drop the rows that contains missing data because they are few (12 missing).
4. according to the column names, we will rename all the column names:
    1. Question       -> `question`
    2. Student Answer -> `student_answer`
    3. Correct Answer -> `reference_answer`
    4. output_label   -> `score`
    5. feedback       -> `rationale`
5. we missed the `mark_scheme` column, but the dataset official documentation includes it, so we'll add it during feature engineering.
6. there is a few full duplications, these we will drop them.
7. the total raw train size 3662 records.
8. there is 106 unique questions.
9. there is 3516 unique student answer.
10. there is 3614 unique feedback.
11. The distribution of `output_label` values is almost balanced, with the largest bias being label `2` and the lowest is `0`.
12. The lengths of students answers vary, from short to long, same thing for feedback which is a good thing for variation.
13. we will drop the full duplicated records.

In [13]:
train_path = os.path.join(raw_datasets, "train.csv")

train_df   = pd.read_csv(train_path)

train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3662 entries, 0 to 3661
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question_id     2953 non-null   float64
 1   Question        3662 non-null   object
 2   Student Answer  3650 non-null   object
 3   Correct Answer  3662 non-null   object
 4   output_label    3662 non-null   int64
 5   feedback        3662 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 171.8+ KB

In [14]:
train_df.sample(5)

,Question_id,Question,Student Answer,Correct Answer,output_label,feedback
2491,30144.0,What is an orthotropic material ?,material having three perpendicular planes of ...,Orthotropic materials have 9 elastic constants...,2,Your answer captures the essence of orthotropi...
3102,76520.0,Usable life of a reservoir is,when the reservoir can still serve after it's ...,"It is the period of time, extending beyond the...",1,Your answer captures the idea that a reservo...
3207,NaN,Q1. State TRUE or FALSE and justify. No correc...,"False, True, done using iret.","False, some other process can also be schedule...",0,"""False, True"" is not a correct response format..."
3293,42541.0,Q1. State TRUE or FALSE and justify. [6 marks]...,"False. In a multitasking case, the same progra...",FALSE\nEach process is an independent entity a...,2,Well done! Your answer clearly explains why th...
2037,NaN,Q1. State TRUE or FALSE and justify. No correc...,False. If any system calls are made by a user ...,"False, OS can use system calls as an event to ...",2,Your answer is correct. You have effectively e...

In [15]:
train_df.isna().sum()

Question_id       709
Question            0
Student Answer     12
Correct Answer      0
output_label        0
feedback            0
dtype: int64

In [16]:
train_df.duplicated().sum()

np.int64(7)

In [17]:
train_df.loc[train_df.duplicated(keep=False)]

,Question_id,Question,Student Answer,Correct Answer,output_label,feedback
214,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nTRUE,"True, pipe system call only allows for one dir...",0,your response is incorrect as no justificatio...
499,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFalse,"True, the user process has no control over whi...",0,incorrect because no justification is provided
589,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFalse,"True, the user process has no control over whi...",0,incorrect because no justification is provided
941,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nTRUE,"True, pipe system call only allows for one dir...",0,your response is incorrect as no justificatio...
1032,NaN,Q1. State TRUE or FALSE and justify. No correc...,FALSE,"False, some other process can also be schedule...",0,incorrect because no justification is provided
1374,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFALSE,"False, only the scheduler can decide which pro...",0,no justification is provided
1410,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFALSE,"False, only the scheduler can decide which pro...",0,no justification is provided
1742,NaN,Q1. State TRUE or FALSE and justify. No correc...,FALSE,"False, some other process can also be schedule...",0,incorrect because no justification is provided
2127,NaN,Q1. State TRUE or FALSE and justify. No correc...,NaN,"True, parent and child are entirely two differ...",0,Incorrect as no answer is provided by the stud...
2158,NaN,Q1. State TRUE or FALSE and justify. No correc...,FALSE,"False, only the scheduler can decide which pro...",0,Incorrect because no justification is provided
2984,NaN,Q1. State TRUE or FALSE and justify. No correc...,FALSE,"False, only the scheduler can decide which pro...",0,Incorrect because no justification is provided
3028,NaN,Q1. State TRUE or FALSE and justify. No correc...,NaN,"False, OS can use system calls as an event to ...",0,Incorrect as no answer is provided by the stud...
3393,NaN,Q1. State TRUE or FALSE and justify. No correc...,NaN,"False, OS can use system calls as an event to ...",0,Incorrect as no answer is provided by the stud...
3497,NaN,Q1. State TRUE or FALSE and justify. No correc...,NaN,"True, parent and child are entirely two differ...",0,Incorrect as no answer is provided by the stud...

In [18]:
train_df["Question_id"].nunique()

97

In [19]:
train_df.loc[train_df["Question_id"].isna()]

,Question_id,Question,Student Answer,Correct Answer,output_label,feedback
0,NaN,Q1. State TRUE or FALSE and justify. No correc...,FALSE,"False, parent and child processes are two inde...",0,Your answer is incorrect. Parent and child pro...
12,NaN,Q1. State TRUE or FALSE and justify. No correc...,"**TRUE**, the OS the the time sharing or conte...","True, the OS can use system calls as an event ...",1,Your answer captures the idea that the OS can ...
14,NaN,Q1. State TRUE or FALSE and justify. No correc...,**TRUE**,"True, parent and child are entirely two differ...",0,The justification provided lacks specific in...
16,NaN,Q1. State TRUE or FALSE and justify. No correc...,TRUE,"True, pipe system call only allows for one dir...",0,your response is incorrect as no justificatio...
17,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nTrue. Scheduling can be done in kernel mode ...,"True, the user process has no control over whi...",2,Your response is accurate. You correctly under...
...,...,...,...,...,...,...
3642,NaN,Q1. State TRUE or FALSE and justify. No correc...,"No, when the interrupt is of implicit-software...","False, some other process can also be schedule...",1,Your response identifies a case where the proc...
3643,NaN,Q1. State TRUE or FALSE and justify. No correc...,"\nTrue, it is possible that the process may no...","True, if the time slice of the process ends wh...",2,Your answer provides a precise and correct exp...
3644,NaN,Q1. State TRUE or FALSE and justify. No correc...,"\n$\rightarrow$ False, there is a chance that ...","False, some other process can also be schedule...",2,Well done! You've correctly identified that ...
3648,NaN,Q1. State TRUE or FALSE and justify. No correc...,"\nTrue, because write permissions are not ther...","True, pipe system call only allows for one dir...",2,Well done! You accurately stated that only uni...
3659,NaN,Q1. State TRUE or FALSE and justify. No correc...,"\nFalse, the order of parent, child execution ...","False, parent and child processes are two inde...",1,Correctly stated that parent and child are ind...

In [20]:
train_df.duplicated(subset="Question").sum()

np.int64(3556)

In [21]:
train_df["Question"].nunique()

106

In [22]:
train_df.loc[train_df.duplicated(subset="Question")]

,Question_id,Question,Student Answer,Correct Answer,output_label,feedback
5,301390.0,To segment the rose petals [4 marks]:,A narrow range around 0 for hue,To segment rose petals\nH (Hue) -- Narrow rang...,1,Your answer is partially correct. While you ...
9,301390.0,To segment the rose petals [4 marks]:,a narrow range around 0 degrees of H,To segment rose petals\nH (Hue) -- Narrow rang...,1,The answer is partially correct. Including h...
10,42544.0,a. List and explain two privileged actions tha...,The program might try to disable the timer in...,- Write to CR3 register to modify page directo...,1,The first response is correct as it identifies...
18,219127.0,Two advantages of separating declaration ...,1) shows all the function declarations of the ...,The code will be more clear and easier for the...,2,Well done! You have correctly identified the...
26,275834.0,Write three parameters which affect ...,"particle size, ultrasonic frequency , tool cro...","Frequency of vibration, Amplitude of vibration...",1,Feedback: You have identified two correct pa...
...,...,...,...,...,...,...
3657,248107.0,What is the role of an equalization tank in wa...,1. to balance the fluctuating flow of water\n2...,The equalization tanks are provided to-\n1. To...,2,Very well done! Your answer precisely aligns w...
3658,248100.0,List four factors affecting water consumption.,1) Climatic conditions b\n2) Geography of the ...,1) Climatic conditions\n2) geography of the re...,2,Excellent work! You have a clear understanding...
3659,NaN,Q1. State TRUE or FALSE and justify. No correc...,"\nFalse, the order of parent, child execution ...","False, parent and child processes are two inde...",1,Correctly stated that parent and child are ind...
3660,42544.0,a. List and explain two privileged actions tha...,Modifying kernel registers - Consider the reg...,- Write to CR3 register to modify page directo...,1,There are two important issues with your answe...
3661,240235.0,What is the principal mechanism of particulate...,microorganisms begin to grow and,bio-filtration ie allowing the microorganisms ...,0,Your answer does not adequately explain the ...

In [23]:
train_df.duplicated(subset="Student Answer").sum()

np.int64(145)

In [24]:
train_df["Student Answer"].nunique()

3516

In [25]:
train_df.loc[train_df.duplicated(subset="Student Answer")]

,Question_id,Question,Student Answer,Correct Answer,output_label,feedback
34,NaN,Q1. State TRUE or FALSE and justify. No correc...,**TRUE**,"True, if the time slice of the process ends wh...",0,Try to explain the scenario better. The reason...
37,NaN,Q1. State TRUE or FALSE and justify. No correc...,FALSE,"False, only the scheduler can decide which pro...",0,Justify your response. User processes do not h...
245,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFalse,"False, some other process can also be schedule...",0,incorrect because no justification is provided
325,324707.0,What is the difference between basin order and...,Order of Basin is the order of its highest ord...,Basin order is highest order of any stream in ...,1,Great observation on the role of channel order...
358,NaN,Q1. State TRUE or FALSE and justify. No correc...,**TRUE**,"True, if the time slice of the process ends wh...",0,no justification is provided
...,...,...,...,...,...,...
3504,NaN,Q1. State TRUE or FALSE and justify. No correc...,True.,"True, if the time slice of the process ends wh...",0,A justification for your answer is required fo...
3524,262097.0,Write any advantage of using TiC/TiN as a tool...,Excellent wear resistance,excellent wear resistance\nthermal stability\n...,2,"That's a good start. However, there are addi..."
3530,42546.0,c. When the fork() system call is made the chi...,4,- When a child process is created and is ready...,0,The provided answer does not address the que...
3569,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFALSE,"False, some other process can also be schedule...",0,The student correctly identified the stateme...
3653,344832.0,Which image analysis applications benefit from...,"Motion detection, Image registration, video tr...",Harris Corner detection from the corner we can...,1,Your answer covers some crucial image analysis...

In [26]:
train_df.duplicated(subset="Correct Answer").sum()

np.int64(3555)

In [27]:
train_df["Correct Answer"].nunique()

107

In [28]:
train_df.loc[train_df.duplicated(subset="Correct Answer")]

,Question_id,Question,Student Answer,Correct Answer,output_label,feedback
5,301390.0,To segment the rose petals [4 marks]:,A narrow range around 0 for hue,To segment rose petals\nH (Hue) -- Narrow rang...,1,Your answer is partially correct. While you ...
9,301390.0,To segment the rose petals [4 marks]:,a narrow range around 0 degrees of H,To segment rose petals\nH (Hue) -- Narrow rang...,1,The answer is partially correct. Including h...
10,42544.0,a. List and explain two privileged actions tha...,The program might try to disable the timer in...,- Write to CR3 register to modify page directo...,1,The first response is correct as it identifies...
18,219127.0,Two advantages of separating declaration ...,1) shows all the function declarations of the ...,The code will be more clear and easier for the...,2,Well done! You have correctly identified the...
26,275834.0,Write three parameters which affect ...,"particle size, ultrasonic frequency , tool cro...","Frequency of vibration, Amplitude of vibration...",1,Feedback: You have identified two correct pa...
...,...,...,...,...,...,...
3657,248107.0,What is the role of an equalization tank in wa...,1. to balance the fluctuating flow of water\n2...,The equalization tanks are provided to-\n1. To...,2,Very well done! Your answer precisely aligns w...
3658,248100.0,List four factors affecting water consumption.,1) Climatic conditions b\n2) Geography of the ...,1) Climatic conditions\n2) geography of the re...,2,Excellent work! You have a clear understanding...
3659,NaN,Q1. State TRUE or FALSE and justify. No correc...,"\nFalse, the order of parent, child execution ...","False, parent and child processes are two inde...",1,Correctly stated that parent and child are ind...
3660,42544.0,a. List and explain two privileged actions tha...,Modifying kernel registers - Consider the reg...,- Write to CR3 register to modify page directo...,1,There are two important issues with your answe...
3661,240235.0,What is the principal mechanism of particulate...,microorganisms begin to grow and,bio-filtration ie allowing the microorganisms ...,0,Your answer does not adequately explain the ...

In [29]:
train_df.duplicated(subset="feedback").sum()

np.int64(48)

In [30]:
train_df["feedback"].nunique()

3614

In [31]:
train_df.loc[train_df.duplicated(subset="feedback")]

,Question_id,Question,Student Answer,Correct Answer,output_label,feedback
132,NaN,Q1. State TRUE or FALSE and justify. No correc...,True.,"False, OS can use system calls as an event to ...",0,incorrect because no justification is provided
214,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nTRUE,"True, pipe system call only allows for one dir...",0,your response is incorrect as no justificatio...
245,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFalse,"False, some other process can also be schedule...",0,incorrect because no justification is provided
499,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFalse,"True, the user process has no control over whi...",0,incorrect because no justification is provided
584,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFALSE,"False, OS can use system calls as an event to ...",0,incorrect because no justification is provided
589,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFalse,"True, the user process has no control over whi...",0,incorrect because no justification is provided
628,NaN,Q1. State TRUE or FALSE and justify. No correc...,TRUE,"False, write can only be done on fd[1] and rea...",0,your response is incorrect as no justificatio...
787,NaN,Q1. State TRUE or FALSE and justify. No correc...,\n**False**,"False, write can only be done on fd[1] and rea...",0,your response is incorrect as no justificatio...
862,NaN,Q1. State TRUE or FALSE and justify. No correc...,**True**,"True, if the time slice of the process ends wh...",0,no justification is provided
941,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nTRUE,"True, pipe system call only allows for one dir...",0,your response is incorrect as no justificatio...
1032,NaN,Q1. State TRUE or FALSE and justify. No correc...,FALSE,"False, some other process can also be schedule...",0,incorrect because no justification is provided
1048,NaN,Q1. State TRUE or FALSE and justify. No correc...,**FALSE**,"False, OS can use system calls as an event to ...",0,incorrect because no justification is provided
1074,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nTrue,"False, write can only be done on fd[1] and rea...",0,your response is incorrect as no justificatio...
1116,NaN,Q1. State TRUE or FALSE and justify. No correc...,\n **FALSE**,"False, some other process can also be schedule...",0,incorrect because no justification is provided
1319,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFalse.\n,"False, OS can use system calls as an event to ...",0,incorrect because no justification is provided
1374,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFALSE,"False, only the scheduler can decide which pro...",0,no justification is provided
1410,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFALSE,"False, only the scheduler can decide which pro...",0,no justification is provided
1480,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nTrue. Obviously.,"False, write can only be done on fd[1] and rea...",0,your response is incorrect as no justificatio...
1572,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFALSE,"False, write can only be done on fd[1] and rea...",0,your response is incorrect as no justificatio...
1646,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nTRUE,"True, the OS can use system calls as an event ...",0,incorrect because no justification is provided
1679,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFALSE,"False, some other process can also be schedule...",0,incorrect because no justification is provided
1706,NaN,Q1. State TRUE or FALSE and justify. No correc...,**False**,"False, write can only be done on fd[1] and rea...",0,your response is incorrect as no justificatio...
1742,NaN,Q1. State TRUE or FALSE and justify. No correc...,FALSE,"False, some other process can also be schedule...",0,incorrect because no justification is provided
1747,NaN,Q1. State TRUE or FALSE and justify. No correc...,\n **FALSE**,"False, write can only be done on fd[1] and rea...",0,your response is incorrect as no justificatio...
1850,NaN,Q1. State TRUE or FALSE and justify. No correc...,FALSE,"True, the user process has no control over whi...",0,incorrect because no justification is provided
2127,NaN,Q1. State TRUE or FALSE and justify. No correc...,NaN,"True, parent and child are entirely two differ...",0,Incorrect as no answer is provided by the stud...
2147,NaN,Q1. State TRUE or FALSE and justify. No correc...,NaN,"False, parent and child processes are two inde...",0,Incorrect as no answer is provided by the stud...
2233,NaN,Q1. State TRUE or FALSE and justify. No correc...,NaN,"False, write can only be done on fd[1] and rea...",0,Incorrect as no answer is provided by the stud...
2252,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFalse,"False, write can only be done on fd[1] and rea...",0,your response is incorrect as no justificatio...
2293,NaN,Q1. State TRUE or FALSE and justify. No correc...,"**True**, Pipes are one-way.","True, pipe system call only allows for one dir...",1,Providing a justification for the correctness ...
2316,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nTrue.\n,"False, write can only be done on fd[1] and rea...",0,your response is incorrect as no justificatio...
2337,NaN,Q1. State TRUE or FALSE and justify. No correc...,\n **TRUE**,"True, pipe system call only allows for one dir...",0,your response is incorrect as no justificatio...
2512,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFALSE,"False, only the scheduler can decide which pro...",0,Incorrect because no justification is provided
2595,NaN,Q1. State TRUE or FALSE and justify. No correc...,FALSE.,"False, write can only be done on fd[1] and rea...",0,your response is incorrect as no justificatio...
2699,NaN,Q1. State TRUE or FALSE and justify. No correc...,NaN,"False, some other process can also be schedule...",0,Incorrect as no answer is provided by the stud...
2776,NaN,Q1. State TRUE or FALSE and justify. No correc...,True.,"True, the user process has no control over whi...",0,incorrect because no justification is provided
2827,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nTRUE.,"False, write can only be done on fd[1] and rea...",0,your response is incorrect as no justificatio...
2882,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nTRUE,"True, the user process has no control over whi...",0,incorrect because no justification is provided
2984,NaN,Q1. State TRUE or FALSE and justify. No correc...,FALSE,"False, only the scheduler can decide which pro...",0,Incorrect because no justification is provided
3005,NaN,Q1. State TRUE or FALSE and justify. No correc...,TRUE,"True, the user process has no control over whi...",0,incorrect because no justification is provided
3012,NaN,Q1. State TRUE or FALSE and justify. No correc...,**TRUE**,"True, the user process has no control over whi...",0,incorrect because no justification is provided
3028,NaN,Q1. State TRUE or FALSE and justify. No correc...,NaN,"False, OS can use system calls as an event to ...",0,Incorrect as no answer is provided by the stud...
3045,NaN,Q1. State TRUE or FALSE and justify. No correc...,FALSE,"False, OS can use system calls as an event to ...",0,incorrect because no justification is provided
3153,NaN,Q1. State TRUE or FALSE and justify. No correc...,NaN,"True, the OS can use system calls as an event ...",0,Incorrect as no answer is provided by the stud...
3268,NaN,Q1. State TRUE or FALSE and justify. No correc...,**False**,"False, OS can use system calls as an event to ...",0,incorrect because no justification is provided
3366,NaN,Q1. State TRUE or FALSE and justify. No correc...,T,"True, pipe system call only allows for one dir...",0,Providing a justification for the correctness ...
3393,NaN,Q1. State TRUE or FALSE and justify. No correc...,NaN,"False, OS can use system calls as an event to ...",0,Incorrect as no answer is provided by the stud...
3497,NaN,Q1. State TRUE or FALSE and justify. No correc...,NaN,"True, parent and child are entirely two differ...",0,Incorrect as no answer is provided by the stud...

In [32]:
train_df["output_label"].value_counts()

output_label
2    1548
1    1268
0     846
Name: count, dtype: int64

In [33]:
train_df["output_label"].value_counts(normalize=True)

output_label
2    0.422720
1    0.346259
0    0.231021
Name: proportion, dtype: float64

In [34]:
train_df.drop(columns=["Question_id"], inplace=True)

In [35]:
train_df.dropna(inplace=True)

In [36]:
train_df.drop_duplicates(inplace=True)

In [37]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3645 entries, 0 to 3661
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question        3645 non-null   object
 1   Student Answer  3645 non-null   object
 2   Correct Answer  3645 non-null   object
 3   output_label    3645 non-null   int64
 4   feedback        3645 non-null   object
dtypes: int64(1), object(4)
memory usage: 170.9+ KB

In [38]:
train_df["output_label"].value_counts()

output_label
2    1548
1    1268
0     829
Name: count, dtype: int64

In [39]:
train_df["output_label"].value_counts(normalize=True)

output_label
2    0.424691
1    0.347874
0    0.227435
Name: proportion, dtype: float64

In [40]:
train_df.loc[train_df.duplicated(subset=["Question", "Student Answer"])]

,Question,Student Answer,Correct Answer,output_label,feedback
325,What is the difference between basin order and...,Order of Basin is the order of its highest ord...,Basin order is highest order of any stream in ...,1,Great observation on the role of channel order...
358,Q1. State TRUE or FALSE and justify. No correc...,**TRUE**,"True, if the time slice of the process ends wh...",0,no justification is provided
554,c. When the fork() system call is made the chi...,4,- When a child process is created and is ready...,0,Your answer is incorrect. The child process do...
568,Two methods of estimating parameters of the pr...,"method of moments, method of maximum likelihood",Method of moments and Method of maximum likeli...,2,That's right! You've correctly identified the ...
627,\nWhat\nis the Full form of RCP?,Representative Concentration Pathway,Representative Concentration Pathway,2,Great! You have provided the accurate full ...
...,...,...,...,...,...
3504,Q1. State TRUE or FALSE and justify. No correc...,True.,"True, if the time slice of the process ends wh...",0,A justification for your answer is required fo...
3524,Write any advantage of using TiC/TiN as a tool...,Excellent wear resistance,excellent wear resistance\nthermal stability\n...,2,"That's a good start. However, there are addi..."
3530,c. When the fork() system call is made the chi...,4,- When a child process is created and is ready...,0,The provided answer does not address the que...
3569,Q1. State TRUE or FALSE and justify. No correc...,\nFALSE,"False, some other process can also be schedule...",0,The student correctly identified the stateme...
3653,Which image analysis applications benefit from...,"Motion detection, Image registration, video tr...",Harris Corner detection from the corner we can...,1,Your answer covers some crucial image analysis...

In [41]:
train_df.loc[train_df.duplicated(subset=["Question", "Student Answer", "Correct Answer"])]

,Question,Student Answer,Correct Answer,output_label,feedback
325,What is the difference between basin order and...,Order of Basin is the order of its highest ord...,Basin order is highest order of any stream in ...,1,Great observation on the role of channel order...
358,Q1. State TRUE or FALSE and justify. No correc...,**TRUE**,"True, if the time slice of the process ends wh...",0,no justification is provided
554,c. When the fork() system call is made the chi...,4,- When a child process is created and is ready...,0,Your answer is incorrect. The child process do...
568,Two methods of estimating parameters of the pr...,"method of moments, method of maximum likelihood",Method of moments and Method of maximum likeli...,2,That's right! You've correctly identified the ...
627,\nWhat\nis the Full form of RCP?,Representative Concentration Pathway,Representative Concentration Pathway,2,Great! You have provided the accurate full ...
...,...,...,...,...,...
3504,Q1. State TRUE or FALSE and justify. No correc...,True.,"True, if the time slice of the process ends wh...",0,A justification for your answer is required fo...
3524,Write any advantage of using TiC/TiN as a tool...,Excellent wear resistance,excellent wear resistance\nthermal stability\n...,2,"That's a good start. However, there are addi..."
3530,c. When the fork() system call is made the chi...,4,- When a child process is created and is ready...,0,The provided answer does not address the que...
3569,Q1. State TRUE or FALSE and justify. No correc...,\nFALSE,"False, some other process can also be schedule...",0,The student correctly identified the stateme...
3653,Which image analysis applications benefit from...,"Motion detection, Image registration, video tr...",Harris Corner detection from the corner we can...,1,Your answer covers some crucial image analysis...

In [42]:
train_df.loc[train_df.duplicated(subset=["Question", "Student Answer", "feedback"])]

Empty DataFrame
Columns: [Question, Student Answer, Correct Answer, output_label, feedback]
Index: []

## Test Dataset (`unseen_answers`)
Here is a summary of the insights and finds of the unseen_answers set:

1. Same as points 1, 2, 3, 4, 5, 6, 11, 12, and 13 in the raw train dataset.
2. the total size is 980 records.
3. there is 103 unique questions.
4. there is 954 unique student answer.
5. there is 963 unique feedback.

In [4]:
test_answers_path = os.path.join(raw_datasets, "unseen_answers.csv")

test_answers_df   = pd.read_csv(test_answers_path)

test_answers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 980 entries, 0 to 979
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question_id     800 non-null    float64
 1   Question        980 non-null    object
 2   Student Answer  978 non-null    object
 3   Correct Answer  980 non-null    object
 4   output_label    980 non-null    int64
 5   feedback        980 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 46.1+ KB

In [44]:
(test_answers_df.sample(5))

,Question_id,Question,Student Answer,Correct Answer,output_label,feedback
256,301392.0,To segment the green leaves and stem [4 marks]:,Broad range of H around 120 degrees and broad ...,Hue should be centered around 120 degrees for ...,2,Excellent! Your answer effectively captures th...
414,346467.0,Why to test the level of significance in hydro...,Level of significance is defined as the fixed ...,The test of level of significance is used to t...,1,Your response correctly defines the level of...
194,219127.0,Two advantages of separating declaration ...,To avoid problems when our class/function /wha...,The code will be more clear and easier for the...,0,The answer is incorrect. It fails to capture...
313,262097.0,Write any advantage of using TiC/TiN as a tool...,"increases hardness, decreases wear, increases ...",excellent wear resistance\nthermal stability\n...,2,Your answer is correct. You have identified ...
376,42541.0,Q1. State TRUE or FALSE and justify. [6 marks]...,"False, as interruptable can be used to instant...",FALSE\nEach process is an independent entity a...,2,That's right! A shared PCB process-control b...

In [45]:
test_answers_df.isna().sum()

Question_id       180
Question            0
Student Answer      2
Correct Answer      0
output_label        0
feedback            0
dtype: int64

In [46]:
test_answers_df.duplicated().sum()

np.int64(2)

In [47]:
test_answers_df.loc[test_answers_df.duplicated(keep=False)]

,Question_id,Question,Student Answer,Correct Answer,output_label,feedback
174,NaN,Q1. State TRUE or FALSE and justify. No correc...,FALSE,"False, some other process can also be schedule...",0,incorrect because no justification is provided
178,NaN,Q1. State TRUE or FALSE and justify. No correc...,FALSE,"False, some other process can also be schedule...",0,incorrect because no justification is provided
847,NaN,Q1. State TRUE or FALSE and justify. No correc...,FALSE,"False, some other process can also be schedule...",0,incorrect because no justification is provided

In [48]:
test_answers_df["Question_id"].nunique()

94

In [49]:
test_answers_df.loc[test_answers_df["Question_id"].isna()]

,Question_id,Question,Student Answer,Correct Answer,output_label,feedback
6,NaN,Q1. State TRUE or FALSE and justify. No correc...,"False, there is no such hindrance from the sta...","False, parent and child processes are two inde...",2,Your answer acknowledges the independence of p...
8,NaN,Q1. State TRUE or FALSE and justify. No correc...,opportunities to schedule READY processes and ...,"True, the OS can use system calls as an event ...",2,Well done! You have successfully identified th...
12,NaN,Q1. State TRUE or FALSE and justify. No correc...,FALSE. It takes some time to restore prev. reg...,"False, some other process can also be schedule...",2,You have correctly identified that the process...
13,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nTrue. If all processes were built such that ...,"True, the OS can use system calls as an event ...",2,Your answer demonstrates a clear understanding...
22,NaN,Q1. State TRUE or FALSE and justify. No correc...,FALSE,"True, the OS can use system calls as an event ...",0,incorrect because no justification is provided
...,...,...,...,...,...,...
940,NaN,Q1. State TRUE or FALSE and justify. No correc...,\n **FALSE**,"False, only the scheduler can decide which pro...",0,Justification: The decision to schedule a proc...
954,NaN,Q1. State TRUE or FALSE and justify. No correc...,"\nTrue: In a co-operative environment, the pro...","True, the OS can use system calls as an event ...",2,Your answer showcases a good understanding of ...
955,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFalse. Scheduling is a privileged operation ...,"False, only the scheduler can decide which pro...",2,Your answer accurately points out that schedul...
965,NaN,Q1. State TRUE or FALSE and justify. No correc...,Ans: FALSE -> OS time sharing program in CPU.,"False, OS can use system calls as an event to ...",1,Your answer points out a fundamental role of t...
974,NaN,Q1. State TRUE or FALSE and justify. No correc...,NaN,"False, write can only be done on fd[1] and rea...",0,Incorrect as no answer is provided by the stud...

In [50]:
test_answers_df.duplicated(subset="Question").sum()

np.int64(877)

In [51]:
test_answers_df["Question"].nunique()

103

In [53]:
test_answers_df.loc[test_answers_df.duplicated(subset="Question")]

,Question_id,Question,Student Answer,Correct Answer,output_label,feedback
4,301390.0,To segment the rose petals [4 marks]:,HSI can decouple the color information and int...,To segment rose petals\nH (Hue) -- Narrow rang...,1,Your answer displays a good understanding of...
5,301390.0,To segment the rose petals [4 marks]:,A narrow range of I centered around 0.33 as R ...,To segment rose petals\nH (Hue) -- Narrow rang...,1,Your answer correctly identifies the narrow ra...
13,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nTrue. If all processes were built such that ...,"True, the OS can use system calls as an event ...",2,Your answer demonstrates a clear understanding...
15,219127.0,Two advantages of separating declaration ...,1.we can separate interface and implementation...,The code will be more clear and easier for the...,1,1. The response could have addressed more poin...
18,219127.0,Two advantages of separating declaration ...,1) This way we can use other structures or cla...,The code will be more clear and easier for the...,2,Your answer indicates a good understanding of ...
...,...,...,...,...,...,...
975,148021.0,Define Priority Inversion in single line.,Using API provided in freertos we can change p...,a higher priority process not getting CPU due ...,0,Your response addresses a way to change task...
976,324832.0,What are the issues that arise when number of ...,Too many hidden layer takes too long to train ...,when the number of hidden layer is very large ...,2,The response captures the key idea of overfitt...
977,324708.0,Why the steeper main streams results in the Hy...,The steeper main streams due to their higher s...,Steeper basin streams allows the run off to l...,1,While your response correctly mentions the fas...
978,42541.0,Q1. State TRUE or FALSE and justify. [6 marks]...,"False, even though multiple processes can be e...",FALSE\nEach process is an independent entity a...,0,Your answer is not entirely correct. While it'...
979,262096.0,Write any limitation of PVD method.,high process cost and low output,coating is thin in nature. complex shapes are...,2,Well done! You have correctly identified tha...

In [5]:
test_answers_df["Student Answer"].nunique()

954

In [6]:
test_answers_df["feedback"].nunique()

963

In [54]:
test_answers_df["output_label"].value_counts()

output_label
2    403
1    344
0    233
Name: count, dtype: int64

In [55]:
test_answers_df["output_label"].value_counts(normalize=True)

output_label
2    0.411224
1    0.351020
0    0.237755
Name: proportion, dtype: float64

In [56]:
test_answers_df.drop(columns=["Question_id"], inplace=True)

In [57]:
test_answers_df.dropna(inplace=True)

In [58]:
test_answers_df.drop_duplicates(inplace=True)

In [59]:
test_answers_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 976 entries, 0 to 979
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question        976 non-null    object
 1   Student Answer  976 non-null    object
 2   Correct Answer  976 non-null    object
 3   output_label    976 non-null    int64
 4   feedback        976 non-null    object
dtypes: int64(1), object(4)
memory usage: 45.8+ KB

In [60]:
test_answers_df["output_label"].value_counts()

output_label
2    403
1    344
0    229
Name: count, dtype: int64

In [61]:
test_answers_df["output_label"].value_counts(normalize=True)

output_label
2    0.412910
1    0.352459
0    0.234631
Name: proportion, dtype: float64

In [62]:
test_answers_df.duplicated(subset=["Question", "Student Answer", "feedback"]).sum()

np.int64(0)

## Test Dataset (`unseen_question`)

Here is a summary of the insights and finds of the unseen_question set:

1. there is no missing values.
2. there is no fully duplications.
3. the total size is 765 records.
4. there is 12 unique questions.
5. there is 751 unique student answer.
6. there is 765 unique feedback.

In [7]:
test_question_path = os.path.join(raw_datasets, "unseen_question.csv")

test_question_df   = pd.read_csv(test_question_path)

test_question_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 765 entries, 0 to 764
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question_id     765 non-null    float64
 1   Question        765 non-null    object
 2   Student Answer  765 non-null    object
 3   Correct Answer  765 non-null    object
 4   output_label    765 non-null    int64
 5   feedback        765 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 36.0+ KB

In [64]:
test_question_df.sample(5)

,Question_id,Question,Student Answer,Correct Answer,output_label,feedback
511,24.0,Q1. State TRUE or FALSE and justify. [6 marks]...,False. CPU provides OS with ISA which builds u...,FALSE\nThe ISA is an abstraction ins...,1,"Your justification is mostly correct. However,..."
192,260815.0,What are the factors that affect the evaporati...,"Storage,Wind,Water Quality, Area, Heat sored, ...","Wind Speed, Temperature of water and air, vapo...",2,Well done! Your answer encompasses the key fac...
441,24.0,Q1. State TRUE or FALSE and justify. [6 marks]...,False - The OS uses the instruction set archit...,FALSE\nThe ISA is an abstraction ins...,2,Well done! You correctly explained that the OS...
201,260815.0,What are the factors that affect the evaporati...,"Surface area, water temperature (air temperatu...","Wind Speed, Temperature of water and air, vapo...",2,Very well explained! Your answer covers all th...
698,23.0,Q1. State TRUE or FALSE and justify. [6 marks]...,False - It is not necessary that the process ...,FALSE\nIf the lock is available a spinlock doe...,2,Well done! You provided a well-reasoned justif...

In [65]:
test_question_df.duplicated().sum()

np.int64(0)

In [66]:
test_question_df["Question_id"].nunique()

12

In [67]:
test_question_df.loc[test_question_df.duplicated(subset="Question")]

,Question_id,Question,Student Answer,Correct Answer,output_label,feedback
1,346456.0,What are the key assumptions of Muskingum floo...,This method assumes a single stage- discharge ...,The Muskingum assumes singles stage. It has th...,1,Your understanding of the singular stage-disch...
2,346456.0,What are the key assumptions of Muskingum floo...,This method assumes a single stage- discharge ...,The Muskingum assumes singles stage. It has th...,1,Your answer highlights one of the key assumpti...
3,346456.0,What are the key assumptions of Muskingum floo...,This method assumes a single stage- discharge ...,The Muskingum assumes singles stage. It has th...,1,Feedback: \n\nYour response correctly iden...
4,346456.0,What are the key assumptions of Muskingum floo...,The Muskingum flood routing method gives the s...,The Muskingum assumes singles stage. It has th...,2,Well done! You have demonstrated a clear under...
5,346456.0,What are the key assumptions of Muskingum floo...,"Assumptions: For every dischange, we take one ...",The Muskingum assumes singles stage. It has th...,1,Feedback: Your understanding of the Muskingu...
...,...,...,...,...,...,...
760,23.0,Q1. State TRUE or FALSE and justify. [6 marks]...,True thats how spinlocks are implemented. They...,FALSE\nIf the lock is available a spinlock doe...,2,Your response acknowledges that a spinlock doe...
761,23.0,Q1. State TRUE or FALSE and justify. [6 marks]...,False. Thread/process will only spin on CPU i...,FALSE\nIf the lock is available a spinlock doe...,2,Your answer is accurate. You correctly stated ...
762,23.0,Q1. State TRUE or FALSE and justify. [6 marks]...,"True, if the lock isn't available, the process...",FALSE\nIf the lock is available a spinlock doe...,1,"Your justification is correct. However, a spin..."
763,23.0,Q1. State TRUE or FALSE and justify. [6 marks]...,True: This is the definition of spinlock. The ...,FALSE\nIf the lock is available a spinlock doe...,2,Your answer demonstrates a clear understanding...
764,23.0,Q1. State TRUE or FALSE and justify. [6 marks]...,False The first process to attempt acquire wil...,FALSE\nIf the lock is available a spinlock doe...,2,Well explained. Keep an eye on the use of pu...

In [68]:
test_question_df.loc[test_question_df.duplicated(subset=["Question", "Student Answer"])]

,Question_id,Question,Student Answer,Correct Answer,output_label,feedback
1,346456.0,What are the key assumptions of Muskingum floo...,This method assumes a single stage- discharge ...,The Muskingum assumes singles stage. It has th...,1,Your understanding of the singular stage-disch...
2,346456.0,What are the key assumptions of Muskingum floo...,This method assumes a single stage- discharge ...,The Muskingum assumes singles stage. It has th...,1,Your answer highlights one of the key assumpti...
20,344833.0,What is the role of edge direction in Harris C...,Edge direction plays an important role as it h...,The role of edge direction in Harris Corner de...,1,Your answer partially addresses the role of ...
53,344833.0,What is the role of edge direction in Harris C...,The role of edge direction in Harris Corner de...,The role of edge direction in Harris Corner de...,2,Excellent! You have a clear understanding of t...
266,260785.0,Expand the term SWOT,surface water and ocean topography,SWOT stands for Strengh Weakness Opportunity T...,0,"""SWOT"" stands for specific business-related fa..."
272,260785.0,Expand the term SWOT,Strength Weakness Opportunity Threat,SWOT stands for Strengh Weakness Opportunity T...,2,Your answer is correct. You have accurately ...
273,260785.0,Expand the term SWOT,strength weakness opportunity threat,SWOT stands for Strengh Weakness Opportunity T...,2,Well done! You have correctly defined the acr...
276,260785.0,Expand the term SWOT,strength weakness opportunity threat,SWOT stands for Strengh Weakness Opportunity T...,2,Well done! You have correctly expanded the SWO...
287,260785.0,Expand the term SWOT,surface water and ocean topography,SWOT stands for Strengh Weakness Opportunity T...,0,The provided answer does not relate to SWOT an...
289,260785.0,Expand the term SWOT,Strength Weakness Opportunity Threat,SWOT stands for Strengh Weakness Opportunity T...,2,Great job! You've correctly expanded the term ...
290,260785.0,Expand the term SWOT,strength weakness opportunities threat,SWOT stands for Strengh Weakness Opportunity T...,2,Well done! You have correctly expanded the SWO...
292,260785.0,Expand the term SWOT,Surface Water and Ocean Topography,SWOT stands for Strengh Weakness Opportunity T...,0,It seems like you are referring to a different...
377,24.0,Q1. State TRUE or FALSE and justify. [6 marks]...,"True, the O.S. need not care about the ISA. It...",FALSE\nThe ISA is an abstraction ins...,0,Your answer implies that the compiler translat...
378,24.0,Q1. State TRUE or FALSE and justify. [6 marks]...,"False, it is still an abstraction layer over m...",FALSE\nThe ISA is an abstraction ins...,2,Well done! You correctly identified the instru...

In [69]:
test_question_df.loc[test_question_df.duplicated(subset=["Question", "Student Answer", "feedback"])]

Empty DataFrame
Columns: [Question_id, Question, Student Answer, Correct Answer, output_label, feedback]
Index: []

In [8]:
test_question_df["Question"].nunique()

12

In [9]:
test_question_df["Student Answer"].nunique()

751

In [10]:
test_question_df["feedback"].nunique()

765

In [70]:
test_question_df["output_label"].value_counts()

output_label
2    321
1    278
0    166
Name: count, dtype: int64

In [71]:
test_question_df["output_label"].value_counts(normalize=True)

output_label
2    0.419608
1    0.363399
0    0.216993
Name: proportion, dtype: float64

In [72]:
test_question_df.drop(columns=["Question_id"], inplace=True)

## Validation Dataset
Here is a summary of the insights and finds of the val set:

1. there is missing values.
2. the is no fully duplications.
3. the total size is 407 records.
4. there is 90 unique questions.
5. there is 400 unique student answer.
6. there is 403 unique feedback.

In [11]:
validation_path = os.path.join(raw_datasets, "val.csv")

validation_df   = pd.read_csv(validation_path)

validation_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question_id     316 non-null    float64
 1   Question        407 non-null    object
 2   Student Answer  405 non-null    object
 3   Correct Answer  407 non-null    object
 4   output_label    407 non-null    int64
 5   feedback        407 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 19.2+ KB

In [74]:
validation_df.sample(5)

,Question_id,Question,Student Answer,Correct Answer,output_label,feedback
92,42541.0,Q1. State TRUE or FALSE and justify. [6 marks]...,"False, each process has its own separate PLB. ...",FALSE\nEach process is an independent entity a...,2,Well done! Your understanding of the reasons b...
206,46882.0,During coagulation process alkalinity reduces ...,anions like co3(2-) get precipitated with meta...,"As coagulation is done,the OH- tend to form mo...",0,Consider looking into the chemical reactions o...
279,226518.0,Describe the purpose of state DecideAction in ...,to decide the next action of the robot when it...,DecideAction node was used to decide which dir...,1,Your response captures the essence of the node...
233,219127.0,Two advantages of separating declaration ...,1 . we can easily figure out which member func...,The code will be more clear and easier for the...,0,The provided answer does not cover key point...
253,131601.0,Define meteorological drought.,happens when dry weather pattern dominantes ov...,meteorological draught is caused by the condit...,1,Your response correctly identifies a key fac...

In [75]:
validation_df.isna().sum()

Question_id       91
Question           0
Student Answer     2
Correct Answer     0
output_label       0
feedback           0
dtype: int64

In [76]:
validation_df.duplicated().sum()

np.int64(0)

In [77]:
validation_df["Question_id"].nunique()

81

In [78]:
validation_df.loc[validation_df["Question_id"].isna()]

,Question_id,Question,Student Answer,Correct Answer,output_label,feedback
3,NaN,Q1. State TRUE or FALSE and justify. No correc...,True.,"True, parent and child are entirely two differ...",0,"Consider the fact that after forking, the chil..."
4,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFalse. The OS can still schedule READY proce...,"False, OS can use system calls as an event to ...",2,Well done for identifying that the operating s...
8,NaN,Q1. State TRUE or FALSE and justify. No correc...,"False**. after the fork(), both the parent an...","True, parent and child are entirely two differ...",0,The write operation in exec doesn't depend o...
27,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFalse. OS decides whether to resume it or sw...,"False, some other process can also be schedule...",2,Your response correctly identifies that choosi...
33,NaN,Q1. State TRUE or FALSE and justify. No correc...,"FALSE, parent process has the ability to initi...","False, only the scheduler can decide which pro...",2,Your understanding of the capabilities of a pa...
...,...,...,...,...,...,...
380,NaN,Q1. State TRUE or FALSE and justify. No correc...,True The second descriptor is write only and t...,"True, pipe system call only allows for one dir...",2,Excellent understanding of the pipe system cal...
388,NaN,Q1. State TRUE or FALSE and justify. No correc...,False.,"False, OS can use system calls as an event to ...",0,incorrect because no justification is provided
391,NaN,Q1. State TRUE or FALSE and justify. No correc...,\nFalse. The scheduling of process is only han...,"False, only the scheduler can decide which pro...",2,Your answer is correct. You accurately stated ...
396,NaN,Q1. State TRUE or FALSE and justify. No correc...,False. It may be rescheduled.,"True, if the time slice of the process ends wh...",0,You are correct that the process may be resche...
399,NaN,Q1. State TRUE or FALSE and justify. No correc...,**False** Data is stored in stack so that it w...,"False, some other process can also be schedule...",1,The answer partially addresses the question by...

In [79]:
validation_df.duplicated(subset="Question").sum()

np.int64(317)

In [12]:
validation_df["Question"].nunique()

90

In [80]:
validation_df["Student Answer"].nunique()

400

In [81]:
validation_df["feedback"].nunique()

403

In [82]:
validation_df["output_label"].value_counts()

output_label
2    168
1    144
0     95
Name: count, dtype: int64

In [83]:
validation_df["output_label"].value_counts(normalize=True)

output_label
2    0.412776
1    0.353808
0    0.233415
Name: proportion, dtype: float64

In [84]:
validation_df.drop(columns=["Question_id"], inplace=True)

In [85]:
validation_df.dropna(inplace=True)

In [86]:
validation_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 405 entries, 0 to 406
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question        405 non-null    object
 1   Student Answer  405 non-null    object
 2   Correct Answer  405 non-null    object
 3   output_label    405 non-null    int64
 4   feedback        405 non-null    object
dtypes: int64(1), object(4)
memory usage: 19.0+ KB

In [87]:
validation_df["output_label"].value_counts()

output_label
2    168
1    144
0     93
Name: count, dtype: int64

In [88]:
validation_df["output_label"].value_counts(normalize=True)

output_label
2    0.414815
1    0.355556
0    0.229630
Name: proportion, dtype: float64

In [89]:
validation_df.duplicated(subset=["Question", "Student Answer", "feedback"]).sum()

np.int64(0)

## Semantic Similarities (Leakages)
Here our goal is to answer these questions: How many leakages is there? What we'll do with them?

Here is the summary about what we did and what we found:
1. convert the dataframes into list of texts, each text represents the concatenated columns value.
2. we used the FAISS (facebook AI similarity search) to see how many semantic similarities between the train set and the others.
3. the threshold is 90%, where filter the records that have similarity score 90% or above.
4. the threshold value wasn’t chosen arbitrarily. we started testing at 80% and increased it gradually. At 80%, too many records were flagged due to repeated `Question` and `Correct Answer`, making the similarity score too high. To reduce false positives and better capture genuinely similar `Student Answer` and `feedback`, we raised the threshold to 90%, which proved to be the most suitable.
5. we used `all-MiniLM-L6-v2` sentence-transformers for embeddings.
6. we used `all-MiniLM-L6-v2` model because it is small, fast and very good for short sentences (~512 tokens).
7. after cleaning the datasets from missing values and direct duplications; here is the total size, leakages, non-leakages for each:
   1. `unseen_answers`: **total size**: 976, **leakages with training set**: 909, **non-leakages**: 67
   2. `unseen_question`: **total size**: 765, **leakages with training set**: 17, **non-leakages**: 748
   3. `val`: **total size**: 405, **leakages with training set**: 376, **non-leakages**: 29
8. the leakage indices are saved in `leakage_indices.json` to use them in the preprocessing stage.

In [90]:
def to_text(df):
    """
    Convert all rows of a DataFrame to concatenated text strings.

    :param df: Pandas DataFrame
    :return: Concatenated text strings
    """
    return df[df.columns.tolist()].astype(str).agg(" ".join, axis=1).tolist()


train_texts         = to_text(train_df)
test_answers_texts  = to_text(test_answers_df)
test_question_texts = to_text(test_question_df)
validation_texts    = to_text(validation_df)

In [91]:
def detect_leakage(query_texts, query_name, index, threshold=0.9, with_info=False):
    """
    Detect potential data leakages by finding query entries (e.g., unseen answers) too similar to training data.

    :param query_texts: list of text entries to check for leakage.
    :param query_name: label used for printing and identification.
    :param index: FAISS index built on normalized training embeddings.
    :param threshold: similarity threshold above which leakage is flagged.
    :return: list of indices in query_texts that are considered leakages.
    """
    query_embeddings = model.encode(query_texts)

    faiss.normalize_L2(query_embeddings)

    D, I             = index.search(query_embeddings, k=1)

    leakage_indices  = [i for i, score in enumerate(D[:, 0]) if score >= threshold]

    if with_info:
        for i in leakage_indices:
            print(f"{query_name}[{i}]: {query_texts[i]}")

            train_match_idx = int(I[i][0])

            print(f"Matched Train[{train_match_idx}]: {train_texts[train_match_idx]}")

            print(f"Similarity: {D[i][0]:.4f}")

            print("=" * 80)

        print(f"Number of Leakages in {query_name}: {len(leakage_indices)}\n")

        return None

    return leakage_indices

In [92]:
model            = SentenceTransformer("all-MiniLM-L6-v2")

train_embeddings = model.encode(train_texts)
faiss.normalize_L2(train_embeddings)
index            = faiss.IndexFlatIP(train_embeddings.shape[1])

index.add(train_embeddings)

### `unseen_answers` & `train`

In [93]:
detect_leakage(query_texts=test_answers_texts, query_name="test_answers_texts", index=index, with_info=True)

test_answers_texts[1]: How is regularized set operation helpful in solid modeling? It helps in joining and maintaining local curvature of two objects. boundaries are defined. no dangling edges. no edges are created extra and no edges are lost while taking intersection of two objects.Regularized set operation helps to follow the defined process in predefined sequence 0   The answer lacks the essential information that regularized set operation in solid modeling helps to define boundaries, eliminate dangling edges, and maintain object integrity during operations like intersection.
Matched Train[1926]: How is regularized set operation helpful in solid modeling? boundaries are defined. no dangling edges. no edges are created extra and no edges are lost while taking intersection of two objects boundaries are defined. no dangling edges. no edges are created extra and no edges are lost while taking intersection of two objects.Regularized set operation helps to follow the defined process in predefined sequence 2 Excellent! You have effectively captured the role of regularized set operations in maintaining precise boundaries, preventing dangling edges, and ensuring efficient intersection operations in solid modeling. Keep building on your understanding of geometric modeling techniques.
Similarity: 0.9702
================================================================================
test_answers_texts[2]: Define Priority Inversion in single line. to assign higher priority to low priority task a higher priority process not getting CPU due to a lower priority process, because the lower priority process holds a resource  1   The student's answer is partially correct. While priority inversion involves assigning higher priority to a lower priority task, the core issue is a higher priority process not getting the CPU due to a lower priority process holding a resource.
Matched Train[2465]: Define Priority Inversion in single line. a higher priority process not getting CPU due to a lower priority process, because the lower priority process holds a resource needed by the higher priority process.  a higher priority process not getting CPU due to a lower priority process, because the lower priority process holds a resource  2 Your answer captures the essence of Priority Inversion effectively. Keep up the good work!
Similarity: 0.9546
================================================================================
test_answers_texts[3]: To segment the rose petals [4 marks]:       H should be around 0-10
S should be greater than 0.5
I should be greater than 0.5 To segment rose petals
H (Hue) -- Narrow range around 0/360 degress ( Red has hue of 0)
S (saturation) -- Close to 0.8-1 (Red is primary color and all primary colors are pure colors)
I (intensity) -- Broad range around 0.5 1 While the ranges provided for H and S are generally accurate, the range for I is incorrect. Red is a dark color, and the intensity value for dark colors typically falls below 0.5.
Matched Train[2787]: To segment the rose petals [4 marks]:       H should be around 0-10
S should be greater than 0.6
I should be greater than 0.6 To segment rose petals
H (Hue) -- Narrow range around 0/360 degress ( Red has hue of 0)
S (saturation) -- Close to 0.8-1 (Red is primary color and all primary colors are pure colors)
I (intensity) -- Broad range around 0.5 1   The range for H is very limited and should not exceed 360 degrees. For I, provide an upper limit. It should also be noted that primary colors like red have a saturation of 1.0.
Similarity: 0.9786
================================================================================
test_answers_texts[4]: To segment the rose petals [4 marks]:       HSI can decouple the color information and intensity information seperately. The values of HSI can be obtained from RGB and can be normalized so that range remains between 0 and 1 .  We can observe that the rose petals have a high intensity and a high hue. Normalized H should be in the range  around 0 to 1/6 as it should be close to the red colour. To segment rose petals
H (Hue) -- Narrow range around 0/360 degress ( Red has hue of 0)
S (saturation) -- Close to 0.8-1 (Red is primary color and all primary colors are pure colors)
I (intensity) -- Broad range around 0.5 1   Your answer displays a good understanding of the HSI color space and its properties. However, you need to link your explanation to the question prompt of segmenting rose petals using HSI. Additionally, avoid stating obvious information not directly relevant to the task at hand.
Matched Train[3500]: To segment the rose petals [4 marks]:       HSI can decouple the color information and intensity information seperately. The values of HSI can be obtained from RGB and can be normalized so that range remains between 0 and 1 .  We can observe that the rose petals have a high intensity and a high hue. Normalized H should be in the range between 0 and 1/6 as it should be close to the red colour. To segment rose petals
H (Hue) -- Narrow range around 0/360 degress ( Red has hue of 0)
S (saturation) -- Close to 0.8-1 (Red is primary color and all primary colors are pure colors)
I (intensity) -- Broad range around 0.5 0   While the answer briefly mentions HSI color space, it does not address the segmentation of rose petals based on HSI as asked in the question.
Similarity: 0.9804
================================================================================
test_answers_texts[5]: To segment the rose petals [4 marks]:       A narrow range of I centered around 0.33 as R is 1 in red region and others are approximately 0
Also, it'll have a narrow range of values of H on 0 degree and 360 degrees To segment rose petals
H (Hue) -- Narrow range around 0/360 degress ( Red has hue of 0)
S (saturation) -- Close to 0.8-1 (Red is primary color and all primary colors are pure colors)
I (intensity) -- Broad range around 0.5 1 Your answer correctly identifies the narrow range of I centered around 0.33 for red petals. However, it does not address the saturation (S) component of the HSI model, which is also important for accurately segmenting rose petals.
Matched Train[2683]: To segment the rose petals [4 marks]:       A narrow range of H around 0 degrees, Intensity(I) centered around 0.5 and Saturation(S) approximately 1 To segment rose petals
H (Hue) -- Narrow range around 0/360 degress ( Red has hue of 0)
S (saturation) -- Close to 0.8-1 (Red is primary color and all primary colors are pure colors)
I (intensity) -- Broad range around 0.5 2 Excellent work! Your answer accurately describes the HSI values for rose petals. You have correctly identified the narrow range for H, centered value for I, and high value for S. Keep up the good work!
Similarity: 0.9422
================================================================================
test_answers_texts[6]: Q1. State TRUE or FALSE and justify. No correct justification, no marks.
e. If a parent process forks a new child process, the exec system call cannot be used in the parent process until the child process terminates. False, there is no such hindrance from the status of the child. The child can be initiated by -init- in future. False, parent and child processes are two independent processes. Parent can perform any operation that it likes including an exec system call. 2 Your answer acknowledges the independence of parent and child processes, correctly stating that the parent process can perform any operation, including an exec system call, regardless of the child's status. Well done!
Matched Train[681]: Q1. State TRUE or FALSE and justify. No correct justification, no marks.
e. If a parent process forks a new child process, the exec system call can be used in the parent process before the child process terminates.
False, we can't. True, parent and child are entirely two different processes. Parent can perform any operation that it wants including exec. 0   Reconsider your response. The parent and child processes are independent entities. The parent process can execute any operation, including exec, regardless of the child process's status.
Similarity: 0.9529
================================================================================
test_answers_texts[7]: Under which circumstances is a multilayer perceptron neural network with multiple hidden layers (&gt;1 layer) desirable? multilayer perceptron NN with multiple hidden layers have more no. of weights. so, more number of weights are required when training data is huge. so that underfitting do not take place. when the model perform poorly on training data, then we can include multiple hidden layers in model when more deep learning or critical learning of features are required, then more hidden layers are required to extract out and learn feautres properly and efficiently so as to perform further tasks well. example- multiclass classification, XOR function  2 Your answer has captured why a multilayer perceptron with multiple hidden layers can be beneficial. In cases where more in-depth feature learning is necessary to adequately execute tasks like multiclass classification or modeling XOR functions, such networks can perform well.
Matched Train[956]: Under which circumstances is a multilayer perceptron neural network with multiple hidden layers (&gt;1 layer) desirable? when we deal with artifical neural network we use >1 layer when more deep learning or critical learning of features are required, then more hidden layers are required to extract out and learn feautres properly and efficiently so as to perform further tasks well. example- multiclass classification, XOR function  0 Your response slightly misses the point. The context of multiple hidden layers in a multilayer perceptron is about allowing the network to learn more complex relationships in the data through additional layers of processing. This enables the network to extract deeper and more intricate features, resulting in better performance.
Similarity: 0.9335
================================================================================
test_answers_texts[8]: Q1. State TRUE or FALSE and justify. No correct justification, no marks.
d. Without the timer interrupt, the OS still has opportunities to schedule READY processes and share the CPU for multitasking opportunities to schedule READY processes and share the CPU for multitasking.  **True**, it still has opportunities because a running process might encounter keyboard interrupt/ exceptions and then some control will shift to OS and some child process will come under execution. True, the OS can use system calls as an event when it schedules some other process on the CPU to run. Various other events can also be seen as opportunities by the OS to perform scheduling operations 2 Well done! You have successfully identified that the OS can still schedule processes without a timer interrupt. Your reasoning is clear and accurate, showing a good understanding of how the system can utilize other events for scheduling purposes. Keep up your good work!
Matched Train[2408]: Q1. State TRUE or FALSE and justify. No correct justification, no marks.
d. Without the timer interrupt, the OS still has opportunities to schedule READY processes and share the CPU for multitasking True. The OS can schedule anything (based on the scheduling algo), if no timer interrupt, this shift can be due to time interval. True, the OS can use system calls as an event when it schedules some other process on the CPU to run. Various other events can also be seen as opportunities by the OS to perform scheduling operations 2 Well done, you correctly identified that the OS can schedule processes in the absence of a timer interrupt. The OS can use other events, such as system calls, to initiate scheduling. Keep exploring other ways in which the OS can perform scheduling operations.
Similarity: 0.9480
================================================================================
test_answers_texts[9]: Two      advantages of separating declaration from definition are: ..... 1) It becomes easier for an user other than the author to understand what all functions are used in a single place and it becomes easier to keep track of all the functions at one place.
2) Code looks very clutter free and afterwards it becomes easier for debugging purposes. The code will be more clear and easier for the reader to understand. Allows easy changing, debugging, and overriding of the functions. Enhances modularity of the code. This also separates the abstraction from the implementation. 2 Excellent! You correctly identified two advantages of separating declaration from definition. Keep up the good work!
Matched Train[685]: Two      advantages of separating declaration from definition are: ..... 1) The code will be more clear and easier for the reader to understand
2) By writing seperately , we can easily override our definition The code will be more clear and easier for the reader to understand. Allows easy changing, debugging, and overriding of the functions. Enhances modularity of the code. This also separates the abstraction from the implementation. 2 Great work! You have identified two of the benefits of separating declaration from definition. Remember, this approach also makes it simpler to update and debug the functions, contributing to the code's flexibility.
Similarity: 0.9741
================================================================================
test_answers_texts[10]: What are the issues that arise when number of hidden layers is very large? when hidden layers are large then Algorithm takes a lot of time to train. Problem of overfitting, where it fails to generalize. Require a lot of training data when the number of hidden layer is very large then the model Contains the high varience problem and it contains overfitting problem due to which it is not able to generalise new unseen data and for training data, the error is less but for testing data, error is high. Back propagation becomes slow 2 Your response correctly identifies the issues that arise when the number of hidden layers is large. You accurately mention overfitting and the need for a large training dataset. However, you could further improve your answer by discussing the problem of high variance or the increased likelihood of learning irrelevant patterns from the training data. This aspect would enhance your explanation of the model's inability to generalize to new data.
Matched Train[1892]: What are the issues that arise when number of hidden layers is very large? It is very difficult to train the model when number of hidden layer re very large. It may also lead to overfitting or memorizing the training data rather than generalise. when the number of hidden layer is very large then the model Contains the high varience problem and it contains overfitting problem due to which it is not able to generalise new unseen data and for training data, the error is less but for testing data, error is high. Back propagation becomes slow 1 Your response highlights a few valid concerns related to having a large number of hidden layers. However, it would be beneficial to provide more specific details about how these issues manifest. Elaborate on why overfitting occurs and how it impacts generalization. Additionally, explain how the training process can be affected by a large number of hidden layers. Try to provide examples or technical explanations to enhance your feedback.
Similarity: 0.9382
================================================================================
test_answers_texts[11]: c. When the fork() system call is made the child process is (almost) identical to the parent
process. In the parent process, the return path from kernel mode to user mode happens via
the trap/interrupt handler (system call is a trap/interrupt).
Explain the return path from the kernel mode to the user mode for the child process.
Specifically, there was no trap in the child process, so how does the child process return from
a trap?  The kernel captures important information like the address of instruction to return to, as well as the return value, among other things, which are required to resume user process execution, in the trapframe.

The way fork behaves is that the child process's trapframe is copied from the parent's trapframe (with a definite change being in the return value of fork()).

Thus, the return-from-trap operation has the access to the information about which instruction address to continue from (eip). This is the same for parent and child, thus both return to the same instruction when scheduled by the scheduler. - When a child process is created and is ready to execute, it is in the kernel mode.
Child process needs context to execute in the kernel mode.
- The context for execution of the child is setup to start execution at the start of a function
(e.g., forkret) and the kernel stack of the child process is setup such that the return address is
set as the return of the trap handler (e.g., trapret)
- As a result, when a child process in the kernel is scheduled, it starts executing in a function
and returns from it to the return address (the trap handler return address).
- This emulates a call to the trap handler and a return from the handler and then proceeds with
the rest of the kernel stack unrolling to return to user space. 1 Your answer correctly identifies that the child process's trapframe is copied from the parent's, allowing both to return to the same instruction when scheduled. However, it doesn't delve into the context setup for the child to start executing in kernel mode. Including this detail would improve your explanation.
Matched Train[1440]: c. When the fork() system call is made the child process is (almost) identical to the parent
process. In the parent process, the return path from kernel mode to user mode happens via
the trap/interrupt handler (system call is a trap/interrupt).
Explain the return path from the kernel mode to the user mode for the child process.
Specifically, there was no trap in the child process, so how does the child process return from
a trap? During fork we also copy trapframe containing saved registers, next instruction pointer etc. So, when child process run after fork, it returns using return address in the trapframe and it's register & starts executing instruction at eip. - When a child process is created and is ready to execute, it is in the kernel mode.
Child process needs context to execute in the kernel mode.
- The context for execution of the child is setup to start execution at the start of a function
(e.g., forkret) and the kernel stack of the child process is setup such that the return address is
set as the return of the trap handler (e.g., trapret)
- As a result, when a child process in the kernel is scheduled, it starts executing in a function
and returns from it to the return address (the trap handler return address).
- This emulates a call to the trap handler and a return from the handler and then proceeds with
the rest of the kernel stack unrolling to return to user space. 1 Great observation! You correctly identified that the child process gets the trapframe from the parent process. However, the crux of the question is how the child process continues execution without the trap occurring. Try to think about how the trapframe information is utilized to facilitate the return.
Similarity: 0.9706
================================================================================
test_answers_texts[12]: Q1. State TRUE or FALSE and justify. No correct justification, no marks.

### `unseen_question` & `train`

In [94]:
detect_leakage(query_texts=test_question_texts, query_name="test_question_texts", index=index, with_info=True)

test_question_texts[348]: During coagulation process alkalinity reduces due to the ___________________________ Formation of metal hydroxide As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 0   The provided response does not address the reduction in alkalinity during the coagulation process. It only mentions the formation of metal hydroxide without explaining the connection to alkalinity reduction.
Matched Train[1754]: During coagulation process alkalinity reduces due to the ___________________________ due to consumption of OH-. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 1   You are on the right track. The alkalinity reduction is due to the consumption of hydroxide ions, but it is also important to recognize that this is a result of the formation of metal hydroxide precipitates, which ultimately leads to an increase in hydrogen ion concentration.
Similarity: 0.9073
================================================================================
test_question_texts[349]: During coagulation process alkalinity reduces due to the ___________________________ Neutralisation of OH- or other alkaline ions As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 1   The response is partially correct. While it accurately identifies the neutralization of OH- as a factor, it would be more comprehensive to mention the specific process that occurs, such as the formation of metal hydroxides or the precipitation of calcium carbonate. Elaborating on this aspect would enhance your understanding.
Matched Train[2567]: During coagulation process alkalinity reduces due to the ___________________________ Reduction of basic ions, because in coagulation, ions coagulates and alkalinity means capacity to neutralizing an acid, thus less basic ions make less neutralization. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 0 It seems that you have a basic understanding of coagulation and its effect on alkalinity. However, your answer can be improved by focusing on the chemical process that occurs during coagulation. Try to explain how the formation of bonds between OH- ions and molecules in the sample leads to a reduction in alkalinity.
Similarity: 0.9094
================================================================================
test_question_texts[355]: During coagulation process alkalinity reduces due to the ___________________________ due to consumption of OH- ions, which precipitates out and shifts the reaction forward. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 0 Your response offers a valid explanation, but it lacks a crucial aspect. The process of coagulation doesn't result in the direct precipitation of OH- ions. Instead, it's the combination of OH- ions with specific molecules in the sample that shifts the reaction equilibrium forward. Consider reviewing the concepts related to the interaction of OH- ions with other molecules during coagulation to better understand this aspect.
Matched Train[2567]: During coagulation process alkalinity reduces due to the ___________________________ Reduction of basic ions, because in coagulation, ions coagulates and alkalinity means capacity to neutralizing an acid, thus less basic ions make less neutralization. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 0 It seems that you have a basic understanding of coagulation and its effect on alkalinity. However, your answer can be improved by focusing on the chemical process that occurs during coagulation. Try to explain how the formation of bonds between OH- ions and molecules in the sample leads to a reduction in alkalinity.
Similarity: 0.9127
================================================================================
test_question_texts[356]: During coagulation process alkalinity reduces due to the ___________________________ reduction in carbonate concentration As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 0   Your response is incorrect. The reduction in OH- ions during coagulation causes an increase in the concentration of H+ ions, resulting in a decrease in alkalinity.
Matched Train[971]: During coagulation process alkalinity reduces due to the ___________________________ Decrease in concentration of hydroxide ions. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 1 Your answer correctly states that the decrease in hydroxide ions is a factor in the reduction of alkalinity during coagulation. However, it does not elaborate on the mechanism behind this decrease, such as the formation of bonds between hydroxide ions and molecules in the sample. Providing a more comprehensive explanation would improve your understanding of the coagulation process.
Similarity: 0.9139
================================================================================
test_question_texts[357]: During coagulation process alkalinity reduces due to the ___________________________ release of H+ by coagulating agent on hydrolysis. Also OH- gets associated with metal and go to coagulation lowering the OH- in solution As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 2   Well done! You correctly understand that the release of H+ ions and the association of OH- ions with the coagulating agent contribute to the reduction in alkalinity during coagulation.
Matched Train[1754]: During coagulation process alkalinity reduces due to the ___________________________ due to consumption of OH-. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 1   You are on the right track. The alkalinity reduction is due to the consumption of hydroxide ions, but it is also important to recognize that this is a result of the formation of metal hydroxide precipitates, which ultimately leads to an increase in hydrogen ion concentration.
Similarity: 0.9574
================================================================================
test_question_texts[358]: During coagulation process alkalinity reduces due to the ___________________________ addition of Metal ions ( e.g Alum) which act as acid and uses OH ion and due to only H plus ions   . hence alkalinity reduces. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 2 Your response demonstrates a solid understanding of the coagulation process. You correctly identified the addition of metal ions, such as alum, as the cause of alkalinity reduction. Your explanation of the chemical reactions involved, including the formation of OH- bonds and the increase in H+ concentration, is accurate and concise. Keep up the good work!
Matched Train[1754]: During coagulation process alkalinity reduces due to the ___________________________ due to consumption of OH-. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 1   You are on the right track. The alkalinity reduction is due to the consumption of hydroxide ions, but it is also important to recognize that this is a result of the formation of metal hydroxide precipitates, which ultimately leads to an increase in hydrogen ion concentration.
Similarity: 0.9381
================================================================================
test_question_texts[359]: During coagulation process alkalinity reduces due to the ___________________________ floc formation due to the ionisation will result in a reduction in alkalinity . As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 0   The provided response contains an incorrect assertion about the cause of alkalinity reduction and does not explain the process accurately. It's essential to understand the role of OH- ions and H+ concentration in determining alkalinity during coagulation.
Matched Train[2308]: During coagulation process alkalinity reduces due to the ___________________________ increase in H+ ion concentration ie lowering of pH. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 2   Your understanding of the coagulation process and its impact on alkalinity is accurate. You correctly identified that an increase in H+ ion concentration and a decrease in pH occur during coagulation. This demonstrates a solid grasp of the underlying chemistry involved.
Similarity: 0.9106
================================================================================
test_question_texts[360]: During coagulation process alkalinity reduces due to the ___________________________ addition of Fe3+ and Al3+ As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 0   The student's answer provides incorrect information. During coagulation, alkalinity reduction occurs due to chemical reactions and certain ions interacting with water molecules, not merely the addition of Fe3+ and Al3+.
Matched Train[1754]: During coagulation process alkalinity reduces due to the ___________________________ due to consumption of OH-. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 1   You are on the right track. The alkalinity reduction is due to the consumption of hydroxide ions, but it is also important to recognize that this is a result of the formation of metal hydroxide precipitates, which ultimately leads to an increase in hydrogen ion concentration.
Similarity: 0.9206
================================================================================
test_question_texts[361]: During coagulation process alkalinity reduces due to the ___________________________ adsorption of carbonate and bicarbonate on the coagulation particles. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 0 The provided response, "adsorption of carbonate and bicarbonate on the coagulation particles," is not a direct cause of alkalinity reduction during coagulation. Please review the coagulation process and the role of hydroxide ions to accurately explain the alkalinity reduction.
Matched Train[971]: During coagulation process alkalinity reduces due to the ___________________________ Decrease in concentration of hydroxide ions. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 1 Your answer correctly states that the decrease in hydroxide ions is a factor in the reduction of alkalinity during coagulation. However, it does not elaborate on the mechanism behind this decrease, such as the formation of bonds between hydroxide ions and molecules in the sample. Providing a more comprehensive explanation would improve your understanding of the coagulation process.
Similarity: 0.9055
================================================================================
test_question_texts[362]: During coagulation process alkalinity reduces due to the ___________________________ the increase in turbidity. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 0   The increase in turbidity is not the reason for the decrease in alkalinity during coagulation.
Matched Train[954]: During coagulation process alkalinity reduces due to the ___________________________ decrease in H+ concentration. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 0   The change in alkalinity during coagulation is not driven by a decrease in H+ concentration. Consider the role of the coagulant in the process and its interaction with the sample.
Similarity: 0.9067
================================================================================
test_question_texts[363]: During coagulation process alkalinity reduces due to the ___________________________ release of protons in a solution . For example Alum As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 0   The student's answer correctly mentions the release of protons. However, it should explain the reason behind this release, which is the formation of more bonds between OH- and the sample molecules.
Matched Train[2308]: During coagulation process alkalinity reduces due to the ___________________________ increase in H+ ion concentration ie lowering of pH. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 2   Your understanding of the coagulation process and its impact on alkalinity is accurate. You correctly identified that an increase in H+ ion concentration and a decrease in pH occur during coagulation. This demonstrates a solid grasp of the underlying chemistry involved.
Similarity: 0.9035
================================================================================
test_question_texts[365]: During coagulation process alkalinity reduces due to the ___________________________ maintainance of pH higher and reduce NOM normal As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 0   The provided answer does not address the change in alkalinity during the coagulation process. It talks about maintaining a higher pH and reducing NOM, which are different aspects of water treatment.
Matched Train[954]: During coagulation process alkalinity reduces due to the ___________________________ decrease in H+ concentration. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 0   The change in alkalinity during coagulation is not driven by a decrease in H+ concentration. Consider the role of the coagulant in the process and its interaction with the sample.
Similarity: 0.9264
================================================================================
test_question_texts[366]: During coagulation process alkalinity reduces due to the ___________________________ formation of larger flocs or precipitates. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 0 The alkalinity reduction during coagulation is not directly linked to the formation of larger flocs or precipitates. The pH level change during coagulation is due to other reactions, such as the formation of metal hydroxides or the release of hydrogen ions from hydrolysis reactions.
Matched Train[1754]: During coagulation process alkalinity reduces due to the ___________________________ due to consumption of OH-. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 1   You are on the right track. The alkalinity reduction is due to the consumption of hydroxide ions, but it is also important to recognize that this is a result of the formation of metal hydroxide precipitates, which ultimately leads to an increase in hydrogen ion concentration.
Similarity: 0.9307
================================================================================
test_question_texts[368]: During coagulation process alkalinity reduces due to the ___________________________ forming precipation with the coagulent As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 0 Coagulation is a process where particles are removed from suspension by the addition of a coagulant, which causes them to form larger particles that can settle out of solution. Alkalinity is a measure of the concentration of hydroxide ions in water. The student's answer is incorrect because the formation of precipitation does not directly cause a reduction in alkalinity.
Matched Train[971]: During coagulation process alkalinity reduces due to the ___________________________ Decrease in concentration of hydroxide ions. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 1 Your answer correctly states that the decrease in hydroxide ions is a factor in the reduction of alkalinity during coagulation. However, it does not elaborate on the mechanism behind this decrease, such as the formation of bonds between hydroxide ions and molecules in the sample. Providing a more comprehensive explanation would improve your understanding of the coagulation process.
Similarity: 0.9067
================================================================================
test_question_texts[369]: During coagulation process alkalinity reduces due to the ___________________________ Due to addition of coagulants, PH decreases due to acidic nature As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 1   The acidity increases because of coagulant addition, not because of its acidic nature. Coagulants neutralize alkalinity by reacting with OH- ions, leading to a decrease in pH.
Matched Train[954]: During coagulation process alkalinity reduces due to the ___________________________ decrease in H+ concentration. As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 0   The change in alkalinity during coagulation is not driven by a decrease in H+ concentration. Consider the role of the coagulant in the process and its interaction with the sample.
Similarity: 0.9556
================================================================================
test_question_texts[370]: During coagulation process alkalinity reduces due to the ___________________________ addition of coagulants and more chlorination As coagulation is done,the OH- tend to form more bonds with the molecules in the sample, and H+ concentration increases which lowers the pH level. 0   The given answer doesn't capture the actual reason behind the reduction of alkalinity. It is caused by the formation of bonds between OH- ions and molecules in the sample, resulting in an increase in H+ ions and lowering of pH level.

### `val` & `train`

In [95]:
detect_leakage(query_texts=validation_texts, query_name="validation_texts", index=index, with_info=True)

validation_texts[0]: Write three      parameters which      affect MRR in ultrasonic machining ? particle size, tool workpiece gap, ultrasonic frequency Frequency of vibration, Amplitude of vibration, Abrasive slurry concentration, Slurry Particle Diameter 1 Feedback:   The answer includes some correct parameters like ultrasonic frequency and particle size. However, tool workpiece gap is not a parameter that affects MRR in ultrasonic machining. Consider including parameters like amplitude of vibration and abrasive slurry concentration to improve the comprehensiveness of the answer.
Matched Train[2938]: Write three      parameters which      affect MRR in ultrasonic machining ? workpiece material, slurry concentration, tool material, static load Frequency of vibration, Amplitude of vibration, Abrasive slurry concentration, Slurry Particle Diameter 1   You have mentioned the parameters that are important for ultrasonic machining but not specifically for MRR. Please check the question again and make sure to focus on factors that influence MRR.
Similarity: 0.9232
================================================================================
validation_texts[1]: c. Assume the OS is using a lazy allocation policy for memory allocation to processes. On a page fault due to an unmapped physical page(and a valid virtual address), the OS handles the page fault (via allocation and updates to the virtual to physical address mappings in the page table) and then executes the next instruction (the one after the faulting instruction).  FALSE
It executes the instruction which caused the page fault. FALSE
Fixing the mapping is only part of operations, the OSes page fault handler creates the
mappings and returns from the handler and re-executes the faulting instruction. On a page
fault the PC is not incremented. 2 Excellent! You accurately identified that the OS would re-execute the faulting instruction rather than proceeding to the next instruction.
Matched Train[1737]: c. Assume the OS is using a lazy allocation policy for memory allocation to processes. On a page fault due to an unmapped physical page(and a valid virtual address), the OS handles the page fault (via allocation and updates to the virtual to physical address mappings in the page table) and then executes the next instruction (the one after the faulting instruction).  False,
after mapping physical address to virtual valid address, then it re-executes that same instruction. FALSE
Fixing the mapping is only part of operations, the OSes page fault handler creates the
mappings and returns from the handler and re-executes the faulting instruction. On a page
fault the PC is not incremented. 2   Excellent job! You accurately explained that the OS re-executes the faulting instruction rather than proceeding to the next one. This shows a clear understanding of the process.
Similarity: 0.9894
================================================================================
validation_texts[2]: Intercepted precipitation by trees reaches earth by __________ and ____________ through fall and stem flow stem flow(flows through stems and branches) and through fall(water falling on earth through leaves) 2 Well done! Your answer reflects a solid understanding of the two main pathways through which intercepted precipitation by trees reaches the earth's surface.
Matched Train[3459]: Intercepted precipitation by trees reaches earth by __________ and ____________ stem flow & through fall stem flow(flows through stems and branches) and through fall(water falling on earth through leaves) 2 Well done! Your answer indicates a solid understanding of the pathways through which intercepted precipitation by trees reaches the earth.
Similarity: 0.9888
================================================================================
validation_texts[3]: Q1. State TRUE or FALSE and justify. No correct justification, no marks.
e. If a parent process forks a new child process, the exec system call can be used in the parent process before the child process terminates. True. True, parent and child are entirely two different processes. Parent can perform any operation that it wants including exec. 0 Consider the fact that after forking, the child process continues executing independently and concurrently with the parent process.
Matched Train[3482]: Q1. State TRUE or FALSE and justify. No correct justification, no marks.
e. If a parent process forks a new child process, the exec system call can be used in the parent process before the child process terminates.
True True, parent and child are entirely two different processes. Parent can perform any operation that it wants including exec. 0 The exec system call cannot be used in the parent process before the child process terminates. The parent will have to wait for child termination in such cases, hence the parent cannot perform any other operations.
Similarity: 0.9808
================================================================================
validation_texts[4]: Q1. State TRUE or FALSE and justify. No correct justification, no marks.
c. Without the timer interrupt, the OS has no opportunities to schedule READY processes and share the CPU for multitasking.
False. The OS can still schedule READY processes if the ongoing process for some reason calls the OS and switches to kernel mode. That reason may differ from the timer interrupt like syscalls / exception. False, OS can use system calls as an event to switch between processes. It won't provide fair execution but still the OS can schedule different processes. 2 Well done for identifying that the operating system can utilize other events like system calls to switch between processes and perform multitasking.
Matched Train[2519]: Q1. State TRUE or FALSE and justify. No correct justification, no marks.
c. Without the timer interrupt, the OS has no opportunities to schedule READY processes and share the CPU for multitasking.
True, without timer interrupt we can't switch b/w processes so only one process will run until completion then next process. False, OS can use system calls as an event to switch between processes. It won't provide fair execution but still the OS can schedule different processes. 0   The system calls can be used by the OS to perform context switching and allow multiple processes to run. Timer interrupts are not the only way to achieve multitasking.
Similarity: 0.9752
================================================================================
validation_texts[5]: What is the difference between the performance of a perceptron classifier and a multilayer perceptron classifier when it is about handling the XOR problem? A perceptron classifier. (simple) can't implement XOR. This is because the classes in xor are not linearly separable, hence we cannot draw a line to separate points [0,0) , (1, 1) ] from [(0, 1), (1, 0) ] But due to non-linear activation function in multilayered percepton, it is easily achievable and hence point can be successfully classified XOR is not linearly separable. A perceptron classifier, which can learn only  linear features can not solve this effectively; while a multilayer perceptron classifier can since it Can learn non-linear features. 2 Your response captures the key difference between the two classifiers and explains why a multilayer perceptron classifier can effectively handle the XOR problem while a perceptron classifier cannot. Keep up the good work!
Matched Train[2746]: What is the difference between the performance of a perceptron classifier and a multilayer perceptron classifier when it is about handling the XOR problem? XOR function is not linearly separable and it requires 2 lines to classify the points. this we will require a more complex multilayer perceptron classifier rather than a perceptron classifier. XOR is not linearly separable. A perceptron classifier, which can learn only  linear features can not solve this effectively; while a multilayer perceptron classifier can since it Can learn non-linear features. 2 Great job! You identified that XOR is not linearly separable and that multilayer perceptron classifiers can handle non-linear patterns more effectively. Remember, multilayer perceptrons can be more complex and require careful tuning of hyperparameters.
Similarity: 0.9352
================================================================================
validation_texts[6]: c. When the fork() system call is made the child process is (almost) identical to the parent
process. In the parent process, the return path from kernel mode to user mode happens via
the trap/interrupt handler (system call is a trap/interrupt).
Explain the return path from the kernel mode to the user mode for the child process.
Specifically, there was no trap in the child process, so how does the child process return from
a trap?  The child process gets created in the Interrupt handler & so trapget gets called as usual at the end & it returns the child process -- So child process also returns via the trap handler itself.

There was no trap in the child process but the child process was created there itself.

Kernel mode to user mode involves changing to PL & Context Switch. - When a child process is created and is ready to execute, it is in the kernel mode.
Child process needs context to execute in the kernel mode.
- The context for execution of the child is setup to start execution at the start of a function
(e.g., forkret) and the kernel stack of the child process is setup such that the return address is
set as the return of the trap handler (e.g., trapret)
- As a result, when a child process in the kernel is scheduled, it starts executing in a function
and returns from it to the return address (the trap handler return address).
- This emulates a call to the trap handler and a return from the handler and then proceeds with
the rest of the kernel stack unrolling to return to user space. 1 The reference answer mentions the specific function "forkret" being used to start the child process and the trap handler being emulated, but your answer does not. Also, include the specifics like "PL" and "Context Switch" in your answer to be more thorough.
Matched Train[2098]: c. When the fork() system call is made the child process is (almost) identical to the parent
process. In the parent process, the return path from kernel mode to user mode happens via
the trap/interrupt handler (system call is a trap/interrupt).
Explain the return path from the kernel mode to the user mode for the child process.
Specifically, there was no trap in the child process, so how does the child process return from
a trap? In child process, there was no trap. - When a child process is created and is ready to execute, it is in the kernel mode.
Child process needs context to execute in the kernel mode.
- The context for execution of the child is setup to start execution at the start of a function
(e.g., forkret) and the kernel stack of the child process is setup such that the return address is
set as the return of the trap handler (e.g., trapret)
- As a result, when a child process in the kernel is scheduled, it starts executing in a function
and returns from it to the return address (the trap handler return address).
- This emulates a call to the trap handler and a return from the handler and then proceeds with
the rest of the kernel stack unrolling to return to user space. 0 A trap is not explicitly set for the child process. However, the context for the child process' execution is set up in a way that it appears as if a trap has occurred. This allows the child process to return to user mode.
Similarity: 0.9773
================================================================================
validation_texts[7]: c. When the fork() system call is made the child process is (almost) identical to the parent
process. In the parent process, the return path from kernel mode to user mode happens via
the trap/interrupt handler (system call is a trap/interrupt).
Explain the return path from the kernel mode to the user mode for the child process.
Specifically, there was no trap in the child process, so how does the child process return from
a trap?  As part of the fork() syscall implementation,
we copy trapframe of parent to child.
we copy return odds of trap function from parent
stack to child stack.
this ensures that the child will return from trap function
same as that of the parent.
the return addr is instruction next to trap function call
In the syscall function.
-> now it looks like parent, child process called syscall it
is handled as 3
now they are ready to move to user mode
-> once copy of both child, parent are same.
After returning to user mode, depending on
scheduler, both starts executing from the same instruction. - When a child process is created and is ready to execute, it is in the kernel mode.
Child process needs context to execute in the kernel mode.
- The context for execution of the child is setup to start execution at the start of a function
(e.g., forkret) and the kernel stack of the child process is setup such that the return address is
set as the return of the trap handler (e.g., trapret)
- As a result, when a child process in the kernel is scheduled, it starts executing in a function
and returns from it to the return address (the trap handler return address).
- This emulates a call to the trap handler and a return from the handler and then proceeds with
the rest of the kernel stack unrolling to return to user space. 1   Your answer correctly identifies the copying of trapframe and return odds from the parent to the child process. However, you did not mention the setup of the child process's context in the kernel mode to start execution at the start of a function like forkret. Including this detail would make your response more comprehensive.
Matched Train[3290]: c. When the fork() system call is made the child process is (almost) identical to the parent
process. In the parent process, the return path from kernel mode to user mode happens via
the trap/interrupt handler (system call is a trap/interrupt).
Explain the return path from the kernel mode to the user mode for the child process.
Specifically, there was no trap in the child process, so how does the child process return from
a trap? In the fork() syscall, when everything is being copied from parent to the child, it also creates a trapframe in the child process. The trapframe in the parent process has return value of 0 while in the newly allocated process (for the child), to rid of the kernel part of syscall is also copied when the child then gets scheduled, it sets a trapframe and kernel stack. It is an trap occurred from the child process as well and the trap has has been completely successfully executed with return value of 0. The child then sets up all of its CPU registers while moving from kernel mode to user mode and "takes the value of function call" fork() to be 0. It also copied eip from parent, and hence continues it's execution from that point onwards. - When a child process is created and is ready to execute, it is in the kernel mode.
Child process needs context to execute in the kernel mode.
- The context for execution of the child is setup to start execution at the start of a function
(e.g., forkret) and the kernel stack of the child process is setup such that the return address is
set as the return of the trap handler (e.g., trapret)
- As a result, when a child process in the kernel is scheduled, it starts executing in a function
and returns from it to the return address (the trap handler return address).
- This emulates a call to the trap handler and a return from the handler and then proceeds with
the rest of the kernel stack unrolling to return to user space. 1 Your answer correctly explains how the trapframe and kernel stack are set up in the child process. However, it could be improved by elaborating on how the child process returns from the trap. Specifically, mention that the child process's trapframe is set up to return to the start of the forkret function, which then returns to the trapret function, effectively emulating the return from the trap handler.
Similarity: 0.9699
================================================================================
validation_texts[8]: Q1. State TRUE or FALSE and justify. No correct justification, no marks.
e. If a parent process forks a new child process, the exec system call can be used in the parent process before the child process terminates.  False**. after the fork(), both the parent and child have their own PCB, memory region (even if copy-on-write), because exec is a write operation. It will create the separate address space on the memory for this). So exec can happen before or after the child process termination, it doesn't depend.  True, parent and child are entirely two different processes. Parent can perform any operation that it wants including exec. 0   The write operation in exec doesn't depend on the termination of the child process. The parent and child processes have their own memory regions, so exec can happen before or after the child process terminates.
Matched Train[1672]: Q1. State TRUE or FALSE and justify. No correct justification, no marks.
e. If a parent process forks a new child process, the exec system call can be used in the parent process before the child process terminates.
TRUE. The exec() call can run in parent process before child process terminates shifting the child process to another parent. True, parent and child are entirely two different processes. Parent can perform any operation that it wants including exec. 2 Great job! You understand that in a fork, the parent and child are two separate processes with their own memory and resources. This allows the parent to execute the exec() system call and load a new program without affecting the child process.
Similarity: 0.9249
================================================================================
validation_texts[9]: What is the advantage of a nonlinear discriminant function classifier over a linear one? In some cases like when the data samples are linearly sampled as a class is merged in between of another class, linear classifier will be not work to classify them. If the feature vector of the data points in the feature space are not linearly separable then the linear classifier wont be able to classify over such a datset. On the other hand non linear classifier are better suited at handling such cases as they are able to create more complex decision boundaries. 1 The student response correctly identifies a scenario where a linear classifier falls short. However, it could benefit from elaboration on why nonlinear classifiers excel in such situations. Encourage the student to explore the concept of decision boundaries and how nonlinear classifiers can create more complex ones to accommodate intricate data distributions.
Matched Train[2660]: What is the advantage of a nonlinear discriminant function classifier over a linear one? The non-linear discriminnat function classifier enables to differntiate non-homogentily distribution data. While as linear classifier is unable to discriminate non linear feature space. If the feature vector of the data points in the feature space are not linearly separable then the linear classifier wont be able to classify over such a datset. On the other hand non linear classifier are better suited at handling such cases as they are able to create more complex decision boundaries. 1 The student's answer correctly mentions the main advantage of a nonlinear discriminant function classifier over a linear one: handling non-linearly separable data. However, it lacks further explanation and examples of how non-linear classifiers achieve this. To improve, the answer should delve into the concept of decision boundaries and provide specific scenarios where a non-linear classifier outperforms a linear one.
Similarity: 0.9356

In [96]:
unseen_answers_leakages     = detect_leakage(query_texts=test_answers_texts, query_name="test_answers_texts", index=index)

unseen_answers_non_leakages = len(test_answers_texts) - len(unseen_answers_leakages)

print("Total Size        : ", len(test_answers_texts))
print("Number of Leakages: ", len(unseen_answers_leakages))
print("Non Leakages      : ", unseen_answers_non_leakages)

Total Size        :  976
Number of Leakages:  909
Non Leakages      :  67

In [97]:
unseen_question_leakages     = detect_leakage(query_texts=test_question_texts, query_name="test_question_texts", index=index)

unseen_question_non_leakages = len(test_question_texts) - len(unseen_question_leakages)

print("Total Size        : ", len(test_question_texts))
print("Number of Leakages: ", len(unseen_question_leakages))
print("Non Leakages      : ", unseen_question_non_leakages)

Total Size        :  765
Number of Leakages:  17
Non Leakages      :  748

In [98]:
validation_leakages     = detect_leakage(query_texts=validation_texts , query_name="validation_texts" , index=index)

validation_non_leakages = len(validation_texts) - len(validation_leakages)

print("Total Size        : ", len(validation_texts))
print("Number of Leakages: ", len(validation_leakages))
print("Non Leakages      : ", validation_non_leakages)

Total Size        :  405
Number of Leakages:  376
Non Leakages      :  29

In [99]:
leakage_indices = {"unseen_answers" : unseen_answers_leakages,
                   "unseen_question": unseen_question_leakages,
                   "val"            : validation_leakages}

with open("leakage_indices.json", "w") as file: json.dump(leakage_indices, file, indent=4)

## Inspect Leakages & Non-Leakages
Howe we will take the advantage of leakages and non-leakages?

1. the main reason high similarities that because of the `Question`, `Correct Answer` and `output_label` are duplicated and this is normal, why? because the essential variables are the `Student Answer` and `feedback`, as each student responds differently to the same question. For example, in an exam with 20 students, one question appears 20 times with 20 unique answers and 20 corresponding `feedback`.
2. we will isolate the non-leakage records to use them for validation and test.
3. the split with the most leakages is the `unseen_answers` split, while the split with the fewest leakages is the `unseen_question` split.
4. given the ratio of split size to the number of leakages, the `val` split is unsuitable for direct validation, as it is nearly fully leaky, with only 29 non-leakages records. so, we need to resplit the test and validation data.

 ### `unseen_answers`

In [100]:
test_answers_leakages_df     = test_answers_df.iloc[unseen_answers_leakages]
test_answers_non_leakages_df = test_answers_df.drop(index=test_answers_df.index[unseen_answers_leakages])

In [101]:
test_answers_leakages_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 909 entries, 1 to 979
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question        909 non-null    object
 1   Student Answer  909 non-null    object
 2   Correct Answer  909 non-null    object
 3   output_label    909 non-null    int64
 4   feedback        909 non-null    object
dtypes: int64(1), object(4)
memory usage: 42.6+ KB

In [102]:
test_answers_leakages_df.sample(5)

,Question,Student Answer,Correct Answer,output_label,feedback
57,Q1. State TRUE or FALSE and justify. [6 marks]...,False. When an executable is used to instantia...,FALSE\nEach process is an independent entity a...,2,Your answer correctly states that each process...
117,Cleaning of slow sand filter is done by ...,1.scraping of surface layer of sand and washin...,Cleaning is usually done by scraping the mediu...,1,Response recognizes two common cleaning meth...
810,To segment the green leaves and stem [4 marks]:,a narrow range around 120 degress for H,Hue should be centered around 120 degrees for ...,1,While the range around 120 degrees is approp...
947,a. List and explain two privileged actions tha...,* Accessing memory space.\nOS won't allow use...,- Write to CR3 register to modify page directo...,1,The student has identified access to memory ...
727,What is conveyed by the very low eigenvalues w...,Very low eigen value in PCT imply that those d...,A very low eigen value refers to axes (eigenve...,1,Good job noticing that low eigenvalues can i...

In [103]:
test_answers_non_leakages_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 67 entries, 0 to 975
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question        67 non-null     object
 1   Student Answer  67 non-null     object
 2   Correct Answer  67 non-null     object
 3   output_label    67 non-null     int64
 4   feedback        67 non-null     object
dtypes: int64(1), object(4)
memory usage: 3.1+ KB

In [104]:
test_answers_non_leakages_df.sample(5)

,Question,Student Answer,Correct Answer,output_label,feedback
496,Two methods of estimating parameters of the pr...,normal distribution and standard distribution,Method of moments and Method of maximum likeli...,0,The response does not address methods for esti...
375,Two advantages of separating declaration ...,Runtime Polymorphism- The same function name c...,The code will be more clear and easier for the...,1,While your answer mentions runtime polymorph...
517,"If there is one explanatory variable, regressi...",linear conditional regression and mul,Univariate and Multivariate,0,Make sure to provide both terms. The first t...
416,Write any two limitations of AJM.,"Low material removal rate, not good for operator","Low Material removal rate (MRR) , Limited nozz...",1,Your answer correctly identifies a limitatio...
53,Two methods of estimating parameters of the pr...,probability paper method and chi square test k...,Method of moments and Method of maximum likeli...,0,It appears that you have mentioned methods use...

In [105]:
test_answers_non_leakages_df.duplicated(subset="Student Answer").sum()

np.int64(0)

In [106]:
test_answers_non_leakages_df.duplicated(subset="feedback").sum()

np.int64(0)

 ### `unseen_question`

In [107]:
test_question_leakages_df     = test_question_df.iloc[unseen_question_leakages]
test_question_non_leakages_df = test_question_df.drop(index=test_question_df.index[unseen_question_leakages])

In [108]:
test_question_leakages_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17 entries, 348 to 371
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question        17 non-null     object
 1   Student Answer  17 non-null     object
 2   Correct Answer  17 non-null     object
 3   output_label    17 non-null     int64
 4   feedback        17 non-null     object
dtypes: int64(1), object(4)
memory usage: 816.0+ bytes

In [109]:
test_question_leakages_df.sample(5)

,Question,Student Answer,Correct Answer,output_label,feedback
358,During coagulation process alkalinity reduces ...,addition of Metal ions ( e.g Alum) which act a...,"As coagulation is done,the OH- tend to form mo...",2,Your response demonstrates a solid understandi...
349,During coagulation process alkalinity reduces ...,Neutralisation of OH- or other alkaline ions,"As coagulation is done,the OH- tend to form mo...",1,The response is partially correct. While it ...
360,During coagulation process alkalinity reduces ...,addition of Fe3+ and Al3+,"As coagulation is done,the OH- tend to form mo...",0,The student's answer provides incorrect info...
365,During coagulation process alkalinity reduces ...,maintainance of pH higher and reduce NOM normal,"As coagulation is done,the OH- tend to form mo...",0,The provided answer does not address the cha...
357,During coagulation process alkalinity reduces ...,release of H+ by coagulating agent on hydrolys...,"As coagulation is done,the OH- tend to form mo...",2,Well done! You correctly understand that the...

In [110]:
test_question_non_leakages_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 748 entries, 0 to 764
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question        748 non-null    object
 1   Student Answer  748 non-null    object
 2   Correct Answer  748 non-null    object
 3   output_label    748 non-null    int64
 4   feedback        748 non-null    object
dtypes: int64(1), object(4)
memory usage: 35.1+ KB

In [111]:
test_question_non_leakages_df.sample(5)

,Question,Student Answer,Correct Answer,output_label,feedback
0,What are the key assumptions of Muskingum floo...,This method assumes a single stage- discharge ...,The Muskingum assumes singles stage. It has th...,1,Your answer addresses one of the key assumptio...
186,What are the factors that affect the evaporati...,"Temperature,Relative humidity,pressure","Wind Speed, Temperature of water and air, vapo...",1,Your answer includes some important factors ...
589,Q1. State TRUE or FALSE and justify. [6 marks]...,False.\nA spinlock doesn't always check for l...,FALSE\nIf the lock is available a spinlock doe...,2,Your response accurately explains that a spinl...
237,What is vapor pressure deficit?,difference between saturate and actual vapor p...,the difference between the amount of moisture ...,2,Your answer accurately defines vapor pressure ...
82,Write any ONE limitation of the wireframe mode...,It is difficult and messy (the faces might not...,The representation is ambiguous and one wirefr...,2,Your answer acknowledges that representing a...

In [112]:
test_question_non_leakages_df.duplicated(subset="Student Answer").sum()

np.int64(14)

In [113]:
test_question_non_leakages_df.duplicated(subset="feedback").sum()

np.int64(0)

 ### `val`

In [114]:
validation_leakages_df     = validation_df.iloc[validation_leakages]
validation_non_leakages_df = validation_df.drop(index=validation_df.index[validation_leakages])

In [115]:
validation_leakages_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 376 entries, 0 to 406
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question        376 non-null    object
 1   Student Answer  376 non-null    object
 2   Correct Answer  376 non-null    object
 3   output_label    376 non-null    int64
 4   feedback        376 non-null    object
dtypes: int64(1), object(4)
memory usage: 17.6+ KB

In [116]:
validation_leakages_df.sample(5)

,Question,Student Answer,Correct Answer,output_label,feedback
81,To segment the rose petals [4 marks]:,The rose petals are red (shades of red) in col...,To segment rose petals\nH (Hue) -- Narrow rang...,1,Your answer captured some aspects of the segme...
65,Q1. State TRUE or FALSE and justify. No correc...,True. The OS may schedule any other process w...,"True, if the time slice of the process ends wh...",2,Your answer captures the essence of process sc...
176,Q1. State TRUE or FALSE and justify. No correc...,\nTrue.\nThe exec system call overwrites the c...,"True, parent and child are entirely two differ...",2,Well done! You have clearly understood the con...
305,Q1. State TRUE or FALSE and justify. [6 marks]...,False - Although it is true that an incorrect ...,FALSE\nEach process is an independent entity a...,2,Excellent understanding of the topic. You corr...
118,Write three parameters which affect ...,particle size abrasive fraction frequency toll...,"Frequency of vibration, Amplitude of vibration...",1,"Your answer is partially correct, although you..."

In [117]:
validation_non_leakages_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29 entries, 28 to 392
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question        29 non-null     object
 1   Student Answer  29 non-null     object
 2   Correct Answer  29 non-null     object
 3   output_label    29 non-null     int64
 4   feedback        29 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.4+ KB

In [118]:
validation_non_leakages_df.sample(5)

,Question,Student Answer,Correct Answer,output_label,feedback
319,a. List and explain two privileged actions tha...,1. If user tries to access the IDT (Interrupt...,- Write to CR3 register to modify page directo...,1,"While the examples you provided are accurate, ..."
384,a. List and explain two privileged actions tha...,4. Disabling interrupts - A user process woul...,- Write to CR3 register to modify page directo...,1,Your response includes two valid privileged ...
28,a. List and explain two privileged actions tha...,Expanding process virtual address space:\nA p...,- Write to CR3 register to modify page directo...,1,You have identified possible privileged action...
385,Two advantages of separating declaration ...,1.we can separate interface and implementation...,The code will be more clear and easier for the...,1,Nicely explained! But note that having separ...
330,a. List and explain two privileged actions tha...,Some privileged actions include:\n1. When the...,- Write to CR3 register to modify page directo...,0,The answer contains partially correct informat...

In [119]:
validation_non_leakages_df.duplicated(subset="Student Answer").sum()

np.int64(0)

In [120]:
validation_non_leakages_df.duplicated(subset="feedback").sum()

np.int64(0)

## Test & Validation Splitting Strategy

What should the test and validation splits be and how?

1. concatenated all the non-leakages splits together under the name `unseen`.
2. after the concatenation, there is no fully duplications.
3. there is 14 `Student Answer` are duplicated but all the `feedback` are unique so this is what we expected and what we want.
4. the distribution of `output_label` values is almost balanced, the lowest is `0`.
5. the split size ratio will be 0.4 for the **validation** and 0.6 for the **test**, based on the concatenated `unseen` data.

In [121]:
unseen_dfs = pd.concat([test_answers_non_leakages_df, test_question_non_leakages_df,validation_non_leakages_df], ignore_index=True)

unseen_dfs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 844 entries, 0 to 843
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question        844 non-null    object
 1   Student Answer  844 non-null    object
 2   Correct Answer  844 non-null    object
 3   output_label    844 non-null    int64
 4   feedback        844 non-null    object
dtypes: int64(1), object(4)
memory usage: 33.1+ KB

In [122]:
unseen_dfs.sample(5)

,Question,Student Answer,Correct Answer,output_label,feedback
770,Q1. State TRUE or FALSE and justify. [6 marks]...,False - Each attempt is not necessary to spin...,FALSE\nIf the lock is available a spinlock doe...,2,Your response is correct. You accurately state...
553,Q1. State TRUE or FALSE and justify. [6 marks]...,False ISA to hides the implementation totals o...,FALSE\nThe ISA is an abstraction ins...,2,Your answer correctly identifies that the inst...
755,Q1. State TRUE or FALSE and justify. [6 marks]...,True.\nEach time the process tries to acquire...,FALSE\nIf the lock is available a spinlock doe...,1,Your answer is partially correct. A spinlock m...
44,Give two uses of lasers,it is used in Shopping malls to scan bar code ...,"cutting and welding purpose, used in medical s...",0,The given uses are not typical applications of...
405,Name two common defluoridation techniques,co-precipitation with alum and lime(Nalgonda p...,Nalgonda Process- precipitation with alum and ...,2,Excellent! You have a solid understanding of...

In [123]:
unseen_dfs.duplicated().sum()

np.int64(0)

In [124]:
unseen_dfs.duplicated(subset="Student Answer").sum()

np.int64(14)

In [125]:
unseen_dfs.duplicated(subset="feedback").sum()

np.int64(0)

In [126]:
unseen_dfs["output_label"].value_counts()

output_label
2    337
1    319
0    188
Name: count, dtype: int64

In [127]:
unseen_dfs["output_label"].value_counts(normalize=True)

output_label
2    0.399289
1    0.377962
0    0.222749
Name: proportion, dtype: float64

### Splits Size
`validation`: 844 * 0.4 = 337.6

`test`: 844 * 0.6 = 506.4

In [128]:
validation_size = unseen_dfs.shape[0] * 0.4
test_size       = unseen_dfs.shape[0] * 0.6

validation_size, test_size

(337.6, 506.4)

## Train Splitting Strategy

What should we do with the remaining leakage records? Should we concatenate them with the training set or simply ignore them?
1. concatenated all the leakages splits together under the name `leakages`.
2. there is 3 fully duplications.
3. we dropped the fully duplications.
4. there is 35 duplicated `Student Answer`.
5. there is 18 duplicated `feedback`.
6. we concatenated the train split with `leakages`, the total size 4944.
7. after the concatenation we found:
   1. there is 3 fully duplications.
   2. we dropped the fully duplications.
   3. there is 202 duplicated `Student Answer`.
   4. there is 52 duplicated `feedback`.
   5. we dropped the duplicated `Studnet Answer`.
   6. after dropping the duplicated `Studnet Answer`, the duplicated `feedback` becomes 18.
8. the distribution of `output_label` values is almost balanced, the largest bias being for label `2` and the lowest is `0`.
9. train size before: 4944, train size after: 4735. the total number of dropped records is: 209.
10. there is 107 unique `Question`.

In [129]:
leakages_dfs = pd.concat([test_answers_leakages_df, test_question_leakages_df, validation_leakages_df], ignore_index=True)

leakages_dfs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1302 entries, 0 to 1301
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question        1302 non-null   object
 1   Student Answer  1302 non-null   object
 2   Correct Answer  1302 non-null   object
 3   output_label    1302 non-null   int64
 4   feedback        1302 non-null   object
dtypes: int64(1), object(4)
memory usage: 51.0+ KB

In [130]:
leakages_dfs.sample(5)

,Question,Student Answer,Correct Answer,output_label,feedback
648,Two advantages of separating declaration ...,1. Separating declaration from definition make...,The code will be more clear and easier for the...,1,The answer is partially correct. While you men...
955,Describe the purpose of state DecideAction in ...,It is used to decide upon next corse of action...,DecideAction node was used to decide which dir...,2,Impressive! Your answer accurately captures th...
138,a. List and explain two privileged actions tha...,User process can try to disable interrupts but...,- Write to CR3 register to modify page directo...,1,While disabling interrupts is a privileged a...
730,What is the need to use homogenous coordinates...,rotation and translation can be captured in t...,"for uniform matrix representation of rotation,...",2,Your understanding of the need for homogeneous...
2,To segment the rose petals [4 marks]:,H should be around 0-10\nS should be greater t...,To segment rose petals\nH (Hue) -- Narrow rang...,1,While the ranges provided for H and S are gene...

In [131]:
leakages_dfs.duplicated().sum()

np.int64(3)

In [145]:
leakages_dfs.drop_duplicates(inplace=True)

In [146]:
leakages_dfs.duplicated(subset="Student Answer").sum()

np.int64(35)

In [147]:
leakages_dfs.duplicated(subset="feedback").sum()

np.int64(18)

In [154]:
train_with_similar = pd.concat([train_df, leakages_dfs], ignore_index=True)

train_with_similar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4944 entries, 0 to 4943
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Question        4944 non-null   object
 1   Student Answer  4944 non-null   object
 2   Correct Answer  4944 non-null   object
 3   output_label    4944 non-null   int64
 4   feedback        4944 non-null   object
dtypes: int64(1), object(4)
memory usage: 193.2+ KB

In [155]:
train_with_similar.sample(5)

,Question,Student Answer,Correct Answer,output_label,feedback
3979,What is the role of an equalization tank in wa...,Balance fluctuating concentrations\nTo assist ...,The equalization tanks are provided to-\n1. To...,2,Your response shows a clear understanding of t...
1078,Two advantages of separating declaration ...,1) keeping all the declaration together helps ...,The code will be more clear and easier for the...,0,The provided answer does not address the adv...
730,c. When the fork() system call is made the chi...,"* After fork(), in child eip is set to forkre...",- When a child process is created and is ready...,2,Well done! You have a clear understanding of t...
911,To segment the green leaves and stem [4 marks]:,narrow range around 120 for H and narrow...,Hue should be centered around 120 degrees for ...,1,The selected values for H and I are too narrow...
3222,To segment the green leaves and stem [4 marks]:,"a narrow range around 120 in hue, a wide range...",Hue should be centered around 120 degrees for ...,2,"You correctly identified the ranges for hue,..."

In [156]:
train_with_similar.duplicated().sum()

np.int64(7)

In [157]:
train_with_similar.drop_duplicates(inplace=True)

In [158]:
train_with_similar.duplicated(subset="Student Answer").sum()

np.int64(202)

In [159]:
train_with_similar.duplicated(subset="feedback").sum()

np.int64(52)

In [160]:
train_with_similar.drop_duplicates(subset="Student Answer", inplace=True)

In [162]:
train_with_similar.duplicated(subset="feedback").sum()

np.int64(18)

In [163]:
train_with_similar["Question"].nunique()

107

In [164]:
train_with_similar["output_label"].value_counts()

output_label
2    2048
1    1674
0    1013
Name: count, dtype: int64

In [165]:
train_with_similar["output_label"].value_counts(normalize=True)

output_label
2    0.432524
1    0.353537
0    0.213939
Name: proportion, dtype: float64

### Split Size
train size: 4735 clean records.

In [166]:
train_with_similar.shape

(4735, 5)

## What is the maximum length?

To see, is there need for truncation or not? (based on the model max_length)
1. maximum length (word-based counting) in train: 481 words.
2. maximum length (word-based counting) in unseen: 361 words
3. empty prompt length (word-based counting): 34 words.

Although the text is converted to tokens instead of words, which slightly increases the length, the maximum lengths based on words are still very reasonable. Even when adding the prompt length to the longest entry in the training set, the total reaches only 515 words. Considering the models we are going to use support much larger maximum lengths, there is no need to worry about the truncation.

### `train`

In [167]:
train_with_similar_texts = to_text(train_with_similar)

max_len = max([len(text.split()) for text in train_with_similar_texts])

print("The maximum text length (words) in the train:", max_len)

The maximum text length (words) in the train: 481

### `unseen`

In [168]:
unseen_texts = to_text(unseen_dfs)

max_len = max([len(text.split()) for text in unseen_texts])

print("The maximum text length (words) in the unseen data:", max_len)

The maximum text length (words) in the unseen data: 361

### Empty Prompt

In [169]:
empty_prompt = """### Instruction:
                  Grade the student's answer based on the given mark scheme, and provide both a score and a rationale.

                  ### Input:
                  Question:
                  Reference Answer:
                  Student Answer:
                  Mark Scheme:

                  ### Response:
                  Score: , Rationale: """

print("The static length (words) of the prompt (no values are given):", len(empty_prompt.split()))

The static length (words) of the prompt (no values are given): 34